### ISSUE TITLE
epilog vs epilogue

### ISSUE THREAD

**Issue by antoniocapelo** [bcoe/yargs#100]
Cool lib, started using it and find it very useful! 
However, can't seem to get the epilogue function to work, I get a type error saying that the module doesn't have the epilogue (nor epilog) method.

btw, is there a typo on the docs (epilog vs epilogue) or are they aliases?

**Comment by bcoe** [comment]
mind pasting the code snippet that's failing for me, if you're on `3.2.1` epilogue should be doing the trick:

```js
var argv = require('./')
  .help('help')
  .epilog('for more information visit https://github.com/chevex/yargs')
  .argv;
```

epilog and epilogue are aliases.

**Comment by bcoe** [comment]
@antoniocapelo did you get this sorted out?

**Comment by antoniocapelo** [comment]
@bcoe I'm still to sort it out

    var argv = yargs
    .version(pkg.version, 'v')
    .epilog('for more information visit https://github.com/chevex/yargs')
    .argv;
 
Gives me ``TypeError: Object #<Object> has no method 'epilog'``

**Comment by bcoe** [comment]
Try upgrading to the newest version:

npm install yargs@3.4.4, epilog is definitely a method on yargs -- which makes me  think you're on an old build.

Another thing worth checking, what is yargs equal to in your example above? I wonder if the object has been overwritten somehow. Try `var argv = require('yargs')`

I'd love to sort this out, in case there is an underlying bug.
