### ISSUE TITLE
specify that a key can have a set of values

### ISSUE THREAD

**Issue by bcoe** [bcoe/yargs#101]
When a key can have a limited set of string values, it would be nice to be able to specify this, perhaps:

```js.option({
  foo: {
   default: 'foo',
   possibleValues: ['foo', 'bar']
  }
});```

**Comment by nylen** [comment]
How about `choices` as the method/key name?

**Comment by bcoe** [comment]
@nylen I like `choices`, any thoughts about how we should display it in the usage string?

`[choices: cat, dog, burger]`

**Comment by nylen** [comment]
Sounds fine to me.
