### ISSUE TITLE
remove dependency on string

### ISSUE THREAD

**Issue by bguiz** [bcoe/yargs#106]
The node package `string` modifies `String.prototype` which is a Javascript antipattern - some may agree/ disagree with this.
However, when the same project includes the `shelljs` package as well, things get really messy - `to` and `toEnd` get invoked for no apparent reason:

- `getNativeStringProperties` in `node_modules/yargs/node_modules/string/lib/string.js:681:32`
- calls `String.toEnd` in `node_modules/shelljs/src/common.js:186:23`
- this **really** should not happen, and modifying `String.prototype` appears to be the root cause.

This does not occur with `yargs@1` or `yargs@2`, but it does indeed occur with `yargs@3`.

**Comment by bcoe** [comment]
@bguiz I agree that modifying String.prototype is an antipattern. Having said that, according to the string documentation it should only be modifying the string prototype if you ask it to:

` Originally, it modified the String prototype. But I quickly learned that in JavaScript, this is considered poor practice.`

https://github.com/bcoe/yargs/blob/master/lib/parser.js#L37

Having said this, there it sounds like you're seeing strange behavior around `string`?

**Comment by bcoe** [comment]
@bguiz I like the looks of this library as a drop in replacement:

https://www.npmjs.com/package/morph

give it a shot and see if you continue seeing shelljs problems?

**Comment by bguiz** [comment]
Yeah, don't get me wrong - both `shelljs` and `string` appear to be modifying `String.prototype`. SO the former is to blame too.

In `yargs@3`, this function in `string` is the offender, `getNativeStringProperties` in `node_modules/yargs/node_modules/string/lib/string.js:681:32`.
Despite the efforts to avoid it - highlighted in https://github.com/bcoe/yargs/blob/master/lib/parser.js#L37 - the `getNativeStringProperties` function appears to still be getting called; so I have a feeling that `string`'s documentation might be misleading.

If currently, the only use of the `string` is for camelise and decamelise, I say go for it!

**Comment by bcoe** [comment]
I've swapped out the string dependency in #108, let me know if this fixes the issues you were seeing with shelljs.

**Comment by bguiz** [comment]
Took a while to get around to it, but I have finally tested this fix
with task-yargs and my target application - and this works like a
charm!

Consequently, task-yargs uses the latest yargs, [as of
now](https://github.com/bguiz/task-yargs/tree/v0.1.2)

Thanks for the fix!
W: http://bguiz.com

**Comment by bcoe** [comment]
@bguiz awesome!

Fun fact, I spent all weekend adding bash completion to yargs (and fixing a ton of bugs), would love for you to give it a shot:

https://github.com/bcoe/yargs#completioncmd-description-fn

I won't publish the feature to `latest` until I can get a few people to QA it. But you can test it out by running:

`npm install yargs@next`.

**Comment by bguiz** [comment]
Adding bash completion was already on my radar:
https://github.com/bguiz/task-yargs/issues/3

... but I was looking at using `complete` or `node-tabtab` directly.
Since `yargs` supports it out of the box now, that's even better!
W: http://bguiz.com
