### ISSUE TITLE
Command-specific help

### ISSUE THREAD

**Issue by raine** [bcoe/yargs#111]
What's the correct pattern for showing command-specific help and is there a mechanism for options that are only applicable to specific command?

`cli-app -h` doesn't show which options apply to which commands, so there would have to be some way to print help how a single command is used. Is that up to the developer to implement?

**Comment by raine** [comment]
Found out about `yargs.reset()` and came up with this:

https://github.com/raine/ez-jenkins/blob/master/src/cli/index.ls

The [output](https://github.com/raine/ez-jenkins#usage) is pretty nice now.

Thanks for implementing `reset()`!

**Comment by bcoe** [comment]
@raine awesome, glad that did the trick.
