### ISSUE TITLE
boolean --no-flags

### ISSUE THREAD

**Issue by schnittstabil** [bcoe/yargs#112]
Is there an easy way to provide flags like [`cp`](http://man7.org/linux/man-pages/man1/cp.1.html) does?
> -T, --no-target-directory
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;treat DEST as a normal file

The problem in my view is the requirement of an alias for a `--no-…` flag.
I've tried the following, with limited success (parsing `['-T']` works like expected):
```js
require('yargs')
    .boolean('T')
    .alias('T', ['no-target-directory'])
    .parse(['--no-target-directory'])

{ _: [],
  T: false,
  'no-target-directory': false,
  noTargetDirectory: false,
  'target-directory': false,
  targetDirectory: false,
  '$0': 'node' }
```
```js
require('yargs')
    .boolean('no-target-directory')
    .alias('no-target-directory', ['T'])
    .parse(['--no-target-directory'])

{ _: [],
  'no-target-directory': false,
  T: false,
  noTargetDirectory: false,
  'target-directory': false,
  targetDirectory: false,
  '$0': 'node' }
```

**Comment by bcoe** [comment]
@schnittstabil as you might already know, `--no` has a special meaning in yargs, reversing whatever argument it is the suffix for., so `--no-foo` will result in `argv.foo = false`.

To get the behavior of cp, we could look at how hard it would be to add this syntax:

```js
require('yargs')
    .boolean('T')
    .alias('T', ['--no-target-directory'])
    .parse(['--no-target-directory'])
```

I would expect the output of this to be:

`.parse(['--no-target-directory']) -> ['target-directory': false, targetDirectory: false]`
`.parse(['-T']) -> ['target-directory': false, targetDirectory: false]`

**Comment by schnittstabil** [comment]
@bcoe Oh, I think I oversimplified the code above. I'm seeking for a mixture of `boolean`, `alias` and `default` calls, such that:
```js
var yargs = require('yargs').
    //…
.parse(['--no-target-directory']).targetDirectory; // is falsy
.parse(['-T']).targetDirectory; // is falsy
.parse([]).targetDirectory; // is truthy --- but equals to undefined, with the code above
```
It does not need to be `targetDirectory`, but also `T` and `noTargetDirectory` does not seem to work.

Because of the special meaning of `--no`, I wouldn't have difficulties with:
```js
var yargs = require('yargs')
    .boolean('T')
    .alias('T', ['--no-target-directory'])
    .default('target-directory', true)

yargs.parse(['-T']).targetDirectory; // but sadly this equals to true
```

**Comment by kilianc** [comment]
I was gonna open an issue similar to this, I just want to document the `not` version of a flag that defaults to `true`, for example having `--colors` defaulting to `true` in the help is not very informative, what you want is the `--no-colors` flag. By the time being I am using examples to have a better users experience.

**Comment by bcoe** [comment]
In yargs 4.x, you can now turn various parsing features on and off:

https://github.com/bcoe/yargs/blob/4.x/README.md#configuration

Give it a spin by installing the `next` tag of yargs:

`npm i yargs@next`

**Comment by schnittstabil** [comment]
Many thanks, `boolean-negation: false` is a very clean and elegant solution :+1:
