### ISSUE TITLE
reset() doesn't reset help()

### ISSUE THREAD

**Issue by raine** [bcoe/yargs#113]
```js
var yargs = require('yargs')
var command = yargs
  .usage('Usage: foo <command> [options]')
  .command('bar')
  .help('h')
  .argv._[0];

if (command === 'bar') {
  yargs.reset()
    .usage('$0 bar')
    .option('f', {
      type: 'boolean',
      alias: 'foo'
    })
    .help('h')
    .example('$0 bar', 'print the hello message!')
    .argv
} else {
  yargs.showHelp()
}
```

First run this example with `node foo.js bar -h`. You'l see that it's not running `bar`'s help, but rather the main command's help.

```
$ node foo.js bar -h
Usage: foo <command> [options]

Commands:
  bar    

Options:
  -h  Show help
```

Next, comment line 5, and run the same command again. You'll see that now it's using `bar`'s help correctly.

```
$ node foo.js bar -h 
node foo.js bar

Options:
  -h  Show help

Examples:
  node foo.js bar    print the hello message!
```

**Comment by bcoe** [comment]
@raine unfortunately I'm not quite sure what the best way around this would be, `help()` causes the process to print and exit., so I've been making it so sub-commands have `help()`., but the top level command does not have help -- any thoughts about how to handle this?

**Comment by raine** [comment]
Hmm. Not sure, I just figured it would be nice to communicate in the top-level help that `-h` and `--help` flags exist. I'd also like to be able to specify those for all commands without repeating them in every one of them.

**Comment by bcoe** [comment]
@raine what do you think of this approach for handling sub-commands:

https://github.com/bcoe/yargs/pull/157

I think it gets around the help-forcing-an-exit-problem.

**Comment by bcoe** [comment]
@raine I've been using the approach documented here, for describing sub-commands now:

https://github.com/bcoe/yargs#commandcmd-desc-fn

Basically:

* reset is called automatically, and a blank yargs is passed into the handler for a command.
* the top level argv will still be populated.
  * see the full discussion here: https://github.com/bcoe/yargs/issues/156, we tried to find a convention that was the best of both worlds.

Here's your example code rewritten to take advantage of this new approach:

```js
var yargs = require('./')

var argv = require('./')
  .usage('Usage: foo <command> [options]')
  .command('bar', 'bar command', function(yargs) {
    yargs
      .usage('$0 bar')
      .option('f', {
        type: 'boolean',
        alias: 'foo',
        describe: 'a foo option'
      })
      .help('h')
      .example('$0 bar', 'print the hello message!')
  })
  .help('h')
  .argv

if (~argv._.indexOf('bar')) {
  console.log(argv)
} else {
  yargs.showHelp()
}
```

I think this is pretty slick :+1:. To try things out, `npm install npm@next`.

Feel free to re-open this ticket, or to open new tickets, if you run into any issues.
