### ISSUE TITLE
Manual usage of process.argv seems buggy

### ISSUE THREAD

**Issue by raine** [bcoe/yargs#114]
README says:

> You can pass in the process.argv yourself:
>
> `require('yargs')([ '-x', '1', '-y', '2' ]).argv`
> or use `.parse()` to do the same thing:
>
> `require('yargs').parse([ '-x', '1', '-y', '2' ])`

It seems it's not the same, or I'm using the feature wrong.

Compare these two:

## will not print help

```js
var argv = yargs(process.argv)
  .usage('Usage: hello <command> [options]')
  .command('foo', '123')
  .command('bar', '123')
  .argv;

yargs.showHelp();
```

## will print help

```js
var argv = yargs
  .usage('Usage: hello <command> [options]')
  .command('foo', '123')
  .command('bar', '123')
  .parse(process.argv)

yargs.showHelp();
```

**Comment by bcoe** [comment]
@raine I think I found a bug with the way `yargs`' singleton was created causing this behavior, would you mind giving this branch a try:

https://github.com/bcoe/yargs/pull/117

And letting me know if it fixes your issues.

**Comment by bcoe** [comment]
I found quite a few bugs around the yargs argv singleton, which I've hammered out. I'm not going to publish to `latest` on npm until I can get a few people to test my fixes from the weekend out, but you can install the `next` tag on npm and it should fix your problems.

`npm install yargs@next`
