### ISSUE TITLE
Inconsistent option defaults

### ISSUE THREAD

**Issue by raine** [bcoe/yargs#115]
If you have an option of type `boolean` and you omit the parameter, `argv` will end up having that option as false.

Now, if you have an option of type `number` (I'm not sure if such type exists) and you don't give the parameter, the `argv` object won't have a placeholder key value pair for that option.

I think it would be more consistent if in this case the omitted parameter would at least have an `undefined` or `null` value in the object.

Does this make sense?

**Comment by bcoe** [comment]
There's no `number` type, would the addition of a number type solve the problem?

**Comment by raine** [comment]
I think so.

**Comment by bcoe** [comment]
@raine I think this should do the trick for you:

https://github.com/bcoe/yargs/pull/116

**Comment by bcoe** [comment]
You can test out this fix by installing `yargs@next`, I will publish to latest sometime tomorrow.,

`npm install yargs@next`.

**Comment by raine** [comment]
Thanks for all your hard work!
