### ISSUE TITLE
Changelog.md

### ISSUE THREAD

**Issue by ilanbiala** [bcoe/yargs#120]
It would be nice to have a changelog.md to keep track of new API options, performance changes, features, bug fixes, etc.

**Comment by bcoe** [comment]
@ilanbiala I'd been thinking the same thing, can you think of a good project to emulate? Want to send a pull request?

**Comment by nylen** [comment]
For [`request`](https://github.com/request/request), we used @lalitkapoor's [`github-changes`](https://github.com/lalitkapoor/github-changes), got a couple of features added to version `0.0.14`, and wrote [`release.sh`](https://github.com/request/request/blob/master/release.sh) which, among other things, generates [`CHANGELOG.md`](https://github.com/request/request/blob/master/CHANGELOG.md) from merged pull request titles.

Pros:
- Fully automated (no one wanted to spend time maintaining a changelog manually)
- Reasonably sane result

Cons:
- Includes junk like typo fixes; a list of PRs to exclude and `sed -i` could probably fix this reasonably well

**Comment by ilanbiala** [comment]
@bcoe this can be closed, no?

**Comment by bcoe** [comment]
@ilanbiala :+1: thanks for the idea.
