### ISSUE TITLE
Allow more settings for .option()

### ISSUE THREAD

**Issue by mscdex** [bcoe/yargs#140]
Currently AFAIK there is no way to use the following with a `.option()` object:

```javascript
var args = require('yargs')
  .option('config', {
    // ...
    config: true
  })
  .option('port', {
    // ...

    // notice no actual default set, this logic is done externally
    // as it depends on the values of other options
    defaultDescription: '80 for HTTP and 443 for HTTPS'
  })
  .argv;
```

So the workarounds for these two missing options are:

```javascript
var args = require('yargs')
  .option('config', {
    // ...
  })
  .config('config')
  .option('port', {
    // ...
  })
  // using `null` is necessary as `undefined` does *not* work
  .default('port', null, '80 for HTTP and 443 for HTTPS')
  .argv;
```

**Comment by mscdex** [comment]
Also I'm not sure how to be able to use "dot notation" when using `option()`?

Using `.option('foo.bar', ...)` just results in a flat object with keys like `"foo.bar": undefined` instead of just `foo: undefined` or `foo: {}` if no foo.* arguments were passed or `foo: { bar: 'asdf' }` if `foo.bar` was passed.

**Comment by bcoe** [comment]
@mscdex happy to add a few more fields to option notation, and to figure out why `dot` notation is giving you trouble. Would you mind opening this as a couple issues though:

* an issue for the `dot-notation` bug.
* an issue for the additional parameters you'd like to see added to `option`

Thanks!

**Comment by bcoe** [comment]
@mscdex #226 adds `config=true` to the options array, I don't quite understand the problem you're having with default descriptions:

```js
yargs.option('port', {
  describe: ''80 for HTTP and 443 for HTTPS',
  default: someVariableILoaded
})
```

As for setting defaults, etc, for dot-notation, let's open a separate ticket for this.

**Comment by nexdrew** [comment]
@bcoe I think @mscdex wants to define a description for the default value (not a description for the option itself) via the `option()` object. I think the only way to do this currently is by calling `default()` and either passing a 3rd argument or passing a named function for the 2nd argument.

Seems easy enough to support a `defaultDescription` property on the `option()` object.

**Comment by nexdrew** [comment]
@mscdex Added `defaultDescription` in `yargs@3.21.0`, which also allows you to explicitly define `default` as `undefined` in the `option()` object:

```js
var argv = require('yargs')
  .option('port', {
    defaultDescription: '80 for HTTP and 443 for HTTPS',
    default: undefined // works this way, but not if property omitted
  })
  .argv
```

Please open another issue for the dot notation problem(s). Thanks!
