### ISSUE TITLE
Decouple yargs from argv

### ISSUE THREAD

**Issue by moatazelmasry2** [bcoe/yargs#142]
Is it possible to use yargs without argv. For example pass a custom command string directly into yargs and handles it like handling argv?

**Comment by bcoe** [comment]
Hey @moatazelmasry2, this is totally possible:

```javascript
var yargs = require("yargs")(['--foo', '99'])
        .usage("$0 [options]")
        .option('foo', {
                alias: 'f',
                describe: 'foo argument.'
        });

console.log(yargs.argv);
```

Would that do the trick for you?

**Comment by moatazelmasry2** [comment]
Yes it definitely does. Many thanks
