### ISSUE TITLE
Please add .jcscrc file

### ISSUE THREAD

**Issue by agokjr** [bcoe/yargs#144]
I have a few ideas I want to try. Please add .jcscrc file so I can better match current syntax.

```bash
$jscs --auto-configure *.js */*.js
Checking index.js against the presets
  Preset    #Errors
1 airbnb    429
2 crockford 62
3 google    414
4 grunt     410
5 jquery    577
6 mdcs      533
7 wikimedia 836
8 yandex    49
```

ref [jscs](http://jscs.info)

**Comment by bcoe** [comment]
:+1: doing some research on what the best approach to bringing some style guidelines into yargs would be.

**Comment by bcoe** [comment]
@agokjr based on advice (and the fact that the codebase was already fairly close to it) I've opted to move yargs to the @feross' standard style guide:

https://github.com/feross/standard

Let me know if this does the trick for you :+1:
