### ISSUE TITLE
Documenting non-hypenated arguments which are not commands

### ISSUE THREAD

**Issue by kimmobrunfeldt** [bcoe/yargs#149]
My cli takes two mandatory arguments, which are non-hypenated arguments. They are not "commands" documenting them as commands makes the guide confusing. I also tried to add a multiline string to `.usage()` but it breaks when wrapping is used.

This is how I got it looking without wrapping, using multiline string in .usage:

```
Usage: watch <command> <pattern> [options]

  <command>   command to be executed when a change is detected
              needs to be surrounded with quotes when command contains spaces
  <pattern>   glob pattern to specify files to be watched
              needs to be surrounded with quotes to prevent shell globbing
              guide to globs: https://github.com/isaacs/node-glob#glob-primer

Options:
  -h, --help      Show help
  -d, --debounce  debounce timeout in ms for executing command  [default: 400]
  -v, --version   Show version number
```

That would be a good enough solution if it wouldn't break without `.wrap(null)`. Wrapping trims leading whitespace and removes the indentation made with spaces in the usage string.

Another option would be to support describing mandatory arguments as options: Here's an example of how it could look like:

```
Usage: watch <command> <pattern> [options]

Options:
  <command>       Command to be executed when a change is detected.
                  Needs to be surrounded with quotes when command 
                  contains spaces
  <pattern>       Glob pattern to specify files to be watched.
                  Needs to be surrounded with quotes to prevent shell globbing.
                  Guide to globs: https://github.com/isaacs/node-glob#glob-primer
  -h, --help      Show help
  -d, --debounce  debounce timeout in ms for executing command  [default: 400]
  -v, --version   Show version number
```

Related to: https://github.com/bcoe/yargs/issues/62

**Comment by bcoe** [comment]
@kimmobrunfeldt I've just released `yargs@3.8.0` which refactors the tabular layout of options/commands to use a new layout abstraction I've been working on:

https://www.npmjs.com/package/cliui

You should now be able to get the behavior you're looking for by doing something like this:

```js
    yargs.usage(  "Usage: watch <command> <pattern> [options]\n\n" +
      "  <command>\t  command to be executed when a change is detected needs to be surrounded with quotes when command contains spaces\n" +
      "  <pattern>\t  glob pattern to specify files to be watched needs to be surrounded with quotes to prevent shell globbing guide to globs: https://github.com/isaacs/node-glob#glob-primer"
    )
```

The great thing is wordwrap works as expected, so you get a nice 80-column layout :+1: 

Let me know if this does the trick.
