### ISSUE TITLE
Add possibility to specify number of following arguments

### ISSUE THREAD

**Issue by gossel-j** [bcoe/yargs#15]
Like in python argparse module, add possibility to set if the flag is followd by N arguments or unspecified number of argument.

https://docs.python.org/2.7/library/argparse.html#nargs

**Comment by bcoe** [comment]
@gossel-j give #105 a spin:

npm install yargs@next

It introduces the `nargs` option.

**Comment by bcoe** [comment]
@gossel-j implemented in https://github.com/bcoe/yargs/pull/105, published to npm as `yargs@3.4.4`.
