### ISSUE TITLE
API to set the order of help menu items

### ISSUE THREAD

**Issue by megawac** [bcoe/yargs#152]
Hi I was wondering if you would consider adding an API to set the order of cli help options. This is useful when 2 commands are related to one another (such as an implication)

Another feature that would branch from this would be adding new line separators or groups of commands.

I can provide some examples later if you'd like

**Comment by timmckenzie** [comment]
My application has about 75 command line arguments.  It would be great to be able group them.

**Comment by bcoe** [comment]
@timmckenzie @megawac I like the idea of grouping CLI arguments better, but I'd like to avoid adding too much more logic for composing the parser.

Would the combination of the following make sense:

1. start alphabetically sorting command line arguments.
2. provide a better API for splitting complex CLI apps into multiple sub-commands, see this pull request:
  * https://github.com/bcoe/yargs/pull/157

**Comment by mnquintana** [comment]
@bcoe Any plans to support setting the order of commands? I'd like to be able to [move Atom from optimist to yargs](https://github.com/atom/apm/pull/346#issuecomment-97490887), but we don't really want to change the order of options in the process.

**Comment by bcoe** [comment]
@mnquintana @kevinsawicki, I would love to get apm using yargs. yargs fixes various bugs with optimists' layout engine and parser, and I think is a worthwhile upgrade.

Is argument ordering the main blocker, here are my thoughts:

* I don't like the idea of an API for ordering, I think it complicates things more than they need to be.
* what if arguments were guaranteed to maintain the same order as they are set in, so:

```js
yargs
 .option('foo', {})
 .option('bar', {})
 .option('snuh', {})
```

would output,

```shell
$0
--foo     blah
--bar     blah
--snuh   blah
```

I figure special arguments like `version`, and `help`, would always be appended to the end of the list perhaps?

* as an alternative option, should we just display arguments in alphabetical order?

**Comment by kevinsawicki** [comment]
> Is argument ordering the main blocker

The main blocker to me was the observed layout differences in https://github.com/atom/apm/pull/346#issuecomment-97490887

**Comment by nexdrew** [comment]
Not sure if ordering is still a consideration, but yargs now preserves declaration/insertion order, which is really nice and should satisfy most use-cases. :white_check_mark:

However, grouping has not been addressed yet and would be a really nice feature. Perhaps add a `group` method and `option()` key that maps arguments to a display string?

e.g.

```js
var argv = require('yargs')
  .demand('air').group('air', 'Must have:')
  .demand('food').group('food', 'Must have:')
  .demand('clothes').group('clothes', 'Must have:')
  .default('phone', 'none').group('phone', 'Nice to have:')
  .default('car', 'none').group('car', 'Nice to have:')
  .default('hairline', 'none').group('hairline', 'Nice to have:')
  .help('help').argv
```

or

```js
var argv = require('yargs')
  .option('air', {
    demand: true, group: 'Must have:'
  })
  .option('food', {
    demand: true, group: 'Must have:'
  })
  .option('clothes', {
    demand: true, group: 'Must have:'
  })
  .option('phone', {
    default: 'none', group: 'Nice to have:'
  })
  .option('car', {
    default: 'none', group: 'Nice to have:'
  })
  .option('hairline', {
    default: 'none', group: 'Nice to have:'
  })
  .help('help')
  .argv
```

or maybe

```js
var argv = require('yargs')
  .group('Must have:', {
    'air': { demand: true },
    'food': { demand: true },
    'clothes': { demand: true }
  })
  .group('Nice to have:', {
    'phone': { default: 'none' },
    'car': { default: 'none' },
    'hairline': { default: 'none' }
  })
  .help('help')
  .argv
```

which produces help content like

```
Must have:
  --air                                                               [required]
  --food                                                              [required]
  --clothes                                                           [required]
Nice to have:
  --phone                                                      [default: "none"]
  --car                                                        [default: "none"]
  --hairline                                                   [default: "none"]
Options:
  --help      Show help                                                [boolean]
```

Thoughts?

**Comment by nexdrew** [comment]
@bcoe Thoughts on API to support grouping of options? The grouping would only apply to usage/help output, I assume.

Could also support something like:

```js
var argv = require('yargs')
  .demand('air')
  .demand('food')
  .demand('clothes')
  .group('Must have:', ['air', 'food', 'clothes'])
  .default('phone', 'none')
  .default('car', 'none')
  .default('hairline', 'none')
  .group('Nice to have:', ['phone', 'car', 'hairline'])
  .help('help')
  .argv
```

@megawac @timmckenzie Would something like this satisfy your use case?

**Comment by megawac** [comment]
Yeah, that's similar to what I envision

**Comment by nexdrew** [comment]
Closing in favor of issue #274.
