### ISSUE TITLE
yargs.showHelp(fn) argument name misleading: it takes a log level, not a function

### ISSUE THREAD

**Issue by triccardi-systran** [bcoe/yargs#153]
Since b109ffc1ba0189c8697021086ef6e50077ba3152 yargs.showHelp(fn) takes in fact a log level (like 'error') instead of a function like it did before that commit, and like it hints with its argument naming.

It breaks for example things like that:
```javascript
yargs.showHelp(winston.error);
```

I understand we cannot change back to taking a function as it would break things (and for my example a `console.error = winston.error;` would be enough), but the argument name should be changed from `fn` to `level` as documentation.

**Comment by bcoe** [comment]
@triccardi-systran do you think we should make `showHelp` take a function or a level? or that the documentation is good enough?

Want to try submitting an update to the documentation?

**Comment by triccardi-systran** [comment]
Taking a function like it did before is more generic, so covers more needs, but:
1/ yargs seems to call `console.*` inother locations too, so it's a half-finished feature
2/ it would break current yargs api to change back to a function
3/ `console.error = winston.error;` also works, while also covering issues 1/ & 2/, so just changing the doc is enough for me.

As for the PR, I currently don't have time for this...
