### ISSUE TITLE
Wrap to window size

### ISSUE THREAD

**Issue by ensonic** [bcoe/yargs#155]
First
https://github.com/bcoe/yargs/blob/master/lib/usage.js#L297-300

mentions 100 in the comment and uses 80 in the code :)
What I wonder if there is a way to say ' wrap to window width'. RIght now, I'd need to call:
.wrap(require('window-size').wsize)

**Comment by bcoe** [comment]
@ensonic I've updated the comment to reflect the 80 character default, what do you think a good approach for allowing this would be? perhaps expose an additional argument on yargs which is an alias for `windowSize.wsize`?

`.wrap(yargs.wsize())`

**Comment by bcoe** [comment]
```var argv = require('./')
  .usage('Usage: foo <command> [options]')
  .command('bar', 'bar command', function(yargs) {
    yargs
      .usage('$0 bar')
      .option('f', {
        type: 'boolean',
        alias: 'foo',
        describe: 'a foo option'
      })
      .help('h')
      .example('$0 bar', 'print the hello message!')
  })
  .wrap(yargs.width())
  .help('h')
  .argv
```

**Comment by ensonic** [comment]
yargs.width() or yargs.termWidth() sounds good to me. Thanks!

**Comment by bcoe** [comment]
@ensonic I've added the method `terminalWidth()`, give it a shot and let me know if this does the trick:

`npm install yargs@next`
