### ISSUE TITLE
arguments specific to commands.

### ISSUE THREAD

**Issue by ohjames** [bcoe/yargs#156]
It would be really great if yargs supported git style command-options:

`git -p ls-files --full-name`

Here `-p` is a global argument and `--full-name` is an argument specific to the `ls-files` command.

Thinking about the syntax, to support the above git example maybe it could be:

```javascript
var argv = require('yargs')
  .command('ls-files', 'List the files', function(cmdArgs) {
    cmdArgs.options({ 'full-name': { type: 'boolean' } })
  })
  .options({ p: { type: 'string' } })
  .argv
```

I'm happy to work on the PR for this, just wanted to open the issue first to see if it was something you'd be willing to accept.

**Comment by bcoe** [comment]
@ohjames this has been something on my wish list too, I like the syntax you outline.

**Comment by ohjames** [comment]
Cool, I don't think it would be too much work either!

As for presenting the options, I guess `argv.command.subOption` would be how it would create them. Another thing, currently a `command` can be before or after the flags, in the case a command has flags, then I think you'd want to disable processing of global options after that command.

**Comment by bcoe** [comment]
@ohjames what do you think of this approach, mind trying it out:

https://github.com/bcoe/yargs/pull/157

I think that passing along a `yargs` instance to a handler function, and returning before commands such as `help` can result in an `exit(0)`, gives me the functionality that I was itching for.

**Comment by ohjames** [comment]
@bcoe Ah that's great thanks for working on this. I need this feature for some paid work I'm doing and today is a national holiday, so tomorrow I'll definitely try this.

**Comment by bcoe** [comment]
@ohjames did you get a chance to look at this, hoping to be able to merge tonight.

**Comment by ohjames** [comment]
Testing now will update you in a few hours :)

**Comment by ohjames** [comment]
The package.json entry:
```
    "yargs": "git://github.com/bcoe/yargs#command-yargs"
```



The code:
```javascript
var opts = require('yargs')
  .options({
    g: { alias: 'global', default: 16 }
  })
  .command('command', 'command help', function(yargs) {
    yargs.options({
      s: { alias: 'specific', default: 10 }
    }) 
  })
  .argv
  
console.log(opts)
```

The testing:
```
% node testyo.js
{ _: [], g: 16, global: 16, '$0': 'testyo.js' }
% node testyo.js -g4
{ _: [], g: 4, global: 4, '$0': 'testyo.js' }
% node testyo.js -g4 command -s5
undefined
% node testyo.js -g4 command    
undefined
```

If I remove the third command argument then I don't get the incorrect `undefined`.

**Comment by ohjames** [comment]
One more result:

```bash
% node testyo.js command    
undefined
```

**Comment by bcoe** [comment]
@ohjames this is not how I was picturing things would work, if you register a handler for a command my expectation would be that the function that executes for the command takes precedence.

This would let you have your application logic for the command in the handler as well:

```js
var opts = require('yargs')
  .options({
    g: { alias: 'global', default: 16 }
  })
  .command('command', 'command help', function(yargs) {
    var opts = yargs.options({
      s: { alias: 'specific', default: 10 }
    }).argv

    console.log(argv);
    // application logic for handling this specific command.
  })
  .argv
```

I found myself writing switch statements, etc, to handle specific commands -- it seemed like this would be a nice abstraction.

**Comment by ohjames** [comment]
I see, in that case do I also get the "global options" inside the handler:

```somecommand -v dostuff --big"

If `-v` means verbose you'd want the `dostuff` handler to know about it right. Does that mean the "yargs" instance passed to the command handler will already contain that value when I call `argv` on it?

That would do, although to be honest I'd rather `yarg` was just an argument parser and not also responsible for switching logic in my entire application. So I'd rather see it return `opts` as usual but with nested fields for command-specific arguments e.g.  `command.verbose`.

Either solution would be fine with me though, I could always cache the sub-command arguments within the command handler functions with a bit of extra code.

**Comment by ohjames** [comment]
If calling `argv` on the subcommand handler also merges in the global arguments... then maybe my subcommand arguments could get overridden though (but then again, it might not be a good idea to have command arguments with the same description as global arguments).

**Comment by ohjames** [comment]
Another thing, with your solution there, I still think it would be nice to return the global options just in case I want to use them after the sub-command handlers are finished (in case I want to use the global arguments when I do some clean-up).

**Comment by bcoe** [comment]
@ohjames here's the problem with returning global options, perhaps you have a thought. Here's the use-case I commonly run into:

* running `--help` should return a help message for the whole application and exit.
* running `--help command` should return a help message specific to a command and exit the application.

If a command is called, and handles printing the help message, we want to ensure that the top-level command line parser short circuits. This is true of a few other things that yargs facilitates for you:

* argument validation might be different for the top-level commands vs. the sub-command.
* you might not wish to have `version` print for the top-level, but not if a sub-command is provided.

Any thoughts about how we could have the best of both worlds? i.e., what should `argv` contain if processing has been handled by a sub-command? 

CC: @isaacs

**Comment by bcoe** [comment]
^ @rstacruz, @nylen, @raine any thoughts about this API we've been bikeshedding? Basically it would be nice to register a handler for a `command`, to make it easier to have command specific help, and to cut down on repetitive logic when apps with sub-commands are built.

**Comment by raine** [comment]
Implementing commands without `yargs.reset()` makes sense because that approach is clunky.

The handler I don't know about because I like to keep my argv parsing function stupid and just parse `argv` and return the command used as string and parsed args.

For example:

- [cli/parse.ls](https://github.com/raine/ez-jenkins/blob/master/src/cli/parse.ls) (parses process.argv with yargs; returns `{ command: String, argv: {k, v} }` )
- [cli/index.ls](https://github.com/raine/ez-jenkins/blob/master/src/cli/index.ls) (dispatches parsed argv to some command)

Also, while I use commands in a project, I might not care about the global options feature if there was no use for it, and would simply merge all options to single argv object.

**Comment by bcoe** [comment]
@raine I'm open to alternative suggestions, but having commands define their own help is the most elegant solution I can think of to avoid calling `reset`.

Wanting to define command specific help is a very common pattern I run into, and argument parsing tends to vary on a command by command basis.

**Comment by ohjames** [comment]
I think commands should be able to define their own help... perhaps when a "--help" argument is encountered some state could be set on the related `yargs` object (the one passed to the command function).

Then after the function returns this state could be checked to see if a command used `--help`.

I'm heavily in favour of the mode I suggested for the reasons I've already mentioned (i.e. using functions only for setting command option state, not as a control-flow mechanism) but I'd be really interested to hear the feedback everyone else has on how this should work.

**Comment by ohjames** [comment]
Oh as for

> unning --help should return a help message for the whole application and exit.
> running --help command should return a help message specific to a command and exit the application.

I think it should be ilke git:

`git --help` == global help
`git command --help` == subcommand help.

I feel that `--help command` is more awkward... e.g. `--help` at end == run help... `--help positional` now it acts differently depending on whether `positional` is a command or not. Yuk!

**Comment by ohjames** [comment]
Another reason I prefer `command --help` is that then `--help` is just another sub-argument for `command` like any other command-argument you define besides help. The same way it works for global options.

**Comment by bcoe** [comment]
how is this compromise, CC: @ohjames @raine:

```
var argv = require('./')
  .usage('npm <command>')
  .command('install', 'tis a mighty fine package to install')
  .command('publish', 'shiver me timbers, should you be sharing all that', function (yargs) {
    yargs
      .option('f', {
        alias: 'force',
        description: 'yar, it usually be a bad idea'
      })
      .demand('f')
      .help('h')
      .alias('h', 'help')
      .version(require('./package').version)
  })
  .help('h')
  .alias('h', 'help')
  .demand('cat')
  .version(require('./package').version)
  .argv

console.log(argv)
```

1. I still call reset on yargs prior to passing it into the handler. Otherwise things get really clunky, I don't want the help for a specific command to again list all commands so it's nice for it to start with a fresh yargs.
2. the top level argv is now populated as expected, based on @ohjames request.
  * one could still handle the command itself in the closure, it's up to the developer.
3. I've made `help` and `version` into booealns, this way both `--help command` and `command --help`.

Thoughts, I think this moves towards something I'm happy with, but that better fits your workflow @ohjames.

**Comment by ohjames** [comment]
:+1: What you've implemented there seems to be the best of both worlds, thanks very much for considering all of our feedback on this. I guess I'd call it my "lack of workflow" rather than my "workflow" hehe :100: :+1:

**Comment by bcoe** [comment]
@ohjames awesome \o/, let me know if the code works as advertised and I'll get this merged and published.

**Comment by ohjames** [comment]
@bcoe Cool, if the code is ready I'll test tomorrow.

**Comment by bcoe** [comment]
@ohjames I've published these changes with the `next` tag, so to test:

`npm install yargs@next`.

Feel free to open tickets if you find any bugs, I'll release things for real tomorrow.

**Comment by Grandclosing** [comment]
Sorry to necro an old post; but what's the status of this item? Does yargs support command-specific options?

**Comment by insidewhy** [comment]
@Grandclosing It does, yargs is great, I always choose this argument parser.
