### ISSUE TITLE
issues with "array" parameters

### ISSUE THREAD

**Issue by getify** [bcoe/yargs#162]
I'm having trouble getting "array" type parameters to work. Perhaps I'm missing how to do it, and this can just be an issue about improving the docs. Here's what I'm trying to do:

```
./foobar --greetings=hello world friends --otherparam=...
```

I want `"hello"`, `"world"`, and `"friends"` as three entries in the array for the argument key `greetings`. Of course, I actually want to be able to have any number of entries from one to a hundred or whatever.

Here's how I've tried to set that up:

```js
ARGS = yargs
    .usage(..)
    // ..
    .array("greetings")
    .default("greetings",[],"empty list")
    // ..
```

I even tried adding in an `nargs("greetings",100)`, but that didn't seem to have any effect. It parses "greetings" as an array, but only puts the first value in, leaving the other two param values in `ARGS._` (and thus being incorrectly handled by other parts of my parsing logic).

What am I missing, or is this is a known issue?

**Comment by bcoe** [comment]
@getify thank you for the bug report, arrays were originally implemented with this arg format in mind:

`$0 --greetings greeting1 --greetings greeting2`

Although I can see the format you're outlining being more convenient, it also sounds like we could use more test cases around `nargs`... the problem is, `nargs` will eat argument no matter what which doesn't work great for variable length arrays. Perhaps if you specify an array type, we should eat arguments until the next flag argument?

**Comment by getify** [comment]
> arrays were originally implemented with this arg format in mind:
> 
> `$0 --greetings greeting1 --greetings greeting2`

Yeah the problem with that is that it's not really obvious from the help text being generated that a user has to re-specify the same param name over and over again. When the help text says "array" or "list" or something like that, I think pretty much all users are going to assume space (or maybe comma) delimited lists of values after the param name. I can't remember that I've ever used a CLI program where I had to specify a list in the way you're describing.

> it also sounds like we could use more test cases around nargs... the problem is, nargs will eat argument no matter what which doesn't work great for variable length arrays.

If I do `--greetings=val1 val2 val3`, then `nargs` seems to have no effect and only grabs `val1`. If I do `--greetings val1 val2 val3`, it works. That's very non-intuitive as well. Should/could it do the same with or without the `=` syntax to avoid that pitfall (not just for me but for users of my program)?

> Perhaps if you specify an array type, we should eat arguments until the next flag argument?

That was definitely my assumption, so it seems perfectly natural to me. Or, you could eat arguments until some specific delimiter, kinda like the `--` thing:

```
$0 --greetings=val1 val2 val3 -- --otherparam
```

Of course, it could be some other delimiter too. But easiest to me would be to grab until the next recognized param. If someone wanted a param as one of the values, they could easily surround it by quotes so it's not going to be interpreted as an actual param.

**Comment by bcoe** [comment]
I've implemented some changes to array parsing, based on this discussion:

https://github.com/bcoe/yargs/pull/164

Would you mind trying things out, and letting me know if things are closer to the behavior you expected? I'm always slightly squeamish when touching code in the parser, so your extra set of eyes is greatly appreciated.

**Comment by getify** [comment]
will do ASAP. thanks! :)

**Comment by getify** [comment]
ok, in my little non-exhaustive limited testing, it seems to be doing what i wanted now. ;-)

**Comment by getify** [comment]
love that this works (not that I would do it per se):

```
foo --param=1 2 3 --param 4 5 6 --param=7 --param 8
["1","2","3","4","5","6","7","8"]
```

**Comment by getify** [comment]
:+1: <3 <3

**Comment by pajenkin** [comment]
Please put this in production soon! I am looking at using the same functionality and was having the same issue!

**Comment by bcoe** [comment]
@pajenkin mind trying out the branch, would love the extra testing -- the only thing blocking me from releasing this is a busy week at npm, and I want to make sure I QA properly.

**Comment by bcoe** [comment]
@pajenkin, @getify give things a spin:

`npm install yargs@next`

I'll publish the changes as latest sometime tomorrow.
