### ISSUE TITLE
using optional handler for .command() causes inconsistent / default behavior

### ISSUE THREAD

**Issue by burl** [bcoe/yargs#163]
When using the optional 3rd argument to .command(), yargs behaves as if it has no knowledge of other declared argument types:

```javascript
#!/usr/bin/env node
var argv = require('yargs')
    .boolean('v')
    .command('foo', 'do foo')                 // knows about -v
    .command('bar', 'do bar', function() {})  // as if -v was not declared
    .demand(1)
    .argv;
console.dir([argv.v, argv._])
```

Actual Results:

```shell
localhost$ ./test-yargs.js -v foo
[ true, [ 'foo' ] ]
localhost$ ./test-yargs.js -v bar
[ 'bar', [] ]
```

Expected Results:
```shell
localhost$ ./test-yargs.js -v foo
[ true, [ 'foo' ] ]
localhost$ ./test-yargs.js -v bar
[ true, [ 'bar' ] ]
```

**Comment by bcoe** [comment]
Hey @burl, when you registry a handler for `bar`, it resets the argument parsing as it's passed into the closure. This is so you can document sub-commands. To get the behavior you're looking for, you could do something like this:

```js
#!/usr/bin/env node
var argv = require('yargs')
    .boolean('v')
    .command('foo', 'do foo')                 // knows about -v
    .command('bar', 'do bar', function(yargs) {
       yargs.boolean('v')
           // document options specific to the command `bar`.
    })  // as if -v was not declared
    .demand(1)
    .argv;
console.dir([argv.v, argv._])
```

Any thoughts about how we could better document this. The problem that we're specifically trying to solve, is being able to document sub-commands -- without making documenting the top-level options too confusing.

**Comment by burl** [comment]
Aah, I see now.  I was not expecting the reset state.  Perhaps just calling that out in the explanation for .command() is good enough.

**Comment by burl** [comment]
I was attempting to parse a command line for a git-style interface with the concept of "global switches" in addition to commands and command options/switches.

ie:  command [global-switches...] <subcommand> [other-switches-and-options....]

Git for instance lets one do this:

   git --no-pager log -q

But, not:

   git -q --no-pager log

because '-q' is not a valid global option.

(unfortunately, this is also valid and unambiguous to git:   git -p log -p)

So this is sort of like two contexts, divided by the position of the subcommand. The left context is "global" and the right context is "command".  Argument permutation may only happen within each context -- not across contexts, and the "global" context needs to become "strict" by default.  The option parser needs to know all the valid subcommands as well.

I'm doing this now by splitting process.argv into two arrays at the position of the first "non-option" looking item - then handle each separately.  Its working fine.

**Comment by bcoe** [comment]
Do you think there are any improvements that could be made to the command handling in yargs itself? I'm trying to balance simplicity, with power -- want to be careful not to add too many dials and knobs. But, if you can think of any quick wins, open to suggestions.

**Comment by danielvy** [comment]
I think that this issue should be re-opened and addressed.

Global options should be available to nested commands. This is the behaviour of most command line tools. 

Re-adding the option for every nested command may be a workaround for simple interface but when dealing with larger amount of commands this is less practical and harder to maintain.

For the purpose of displaying help, each command could set whether it wants the global options to be displayed when asking for specific command help (defaults to false).

so:
`mytool --help` displays commands and global options
`mytool command --help` displays command specific options (unless it explicitly asks to display global options, then it should be displayed in separate section).
and `mytool command -g` will include the -g option, even if set outside of the command.

Thanks!

**Comment by nexdrew** [comment]
@danielvy Thanks for the suggestion!

I think we realize that yargs has a deficiency in easily supporting a multi-command interface (see issues #121, #174, #201, #202, #225), but it's a difficult problem to solve, especially when it comes to maintaining multiple contexts of options. For instance, how should `mytool --help command` or `mytool -g command` behave?

I'd be interested to hear what you think about [this proposal](https://github.com/bcoe/yargs/issues/225#issuecomment-129289198) to support an object syntax for defining commands and potential subcommands. It seems a uniform object model would allow us to more easily build command-specific features/configuration going forward (such as if global options should be included or not), and may provide a better way for yargs to handle context switching automatically.

Thoughts?

**Comment by bcoe** [comment]
@danielvy @nexdrew perhaps we could open up a new issue, with a subject heading something like:

`move towards improved v2 version of command handling`?

The command feature is cool, but it's not quite all the way there -- needs improvement.

**Comment by danielvy** [comment]
@nexdrew 

I don't think that there is too much unsolvable ambiguity here. The "command" strings (as opposed to just "flagless" arguments the CLI expects) are known and finite. 

So even if the CLI doesn't restrict a command to a certain position, it is clear what the user expects from the context.

* `mytool --help command` 
	* when the "command" matches a known command string, it should display the help for that command
	* when the "command" doesn't matches a known command string should display the global help
* `mytool -g command ` should behave depending on whether the `-g` flag expects an argument:
	* If it does, it takes precedence and the command is treated as a global argument `-g`. If the user still wants to use the *"command"* as such it has to be done in a way that satisfies the `-g` flag (e.g. `mytool -g argument command`)
	* if it doesn't (e.g. `-g` is just a boolean)
		* if command matches a known command string, it is invoked and passed the `-g` flag
		* if there is no known *"command"*, it should run the default command-less variant (if allowed), pass the -g flag and pass the (unknown) *"command"* as a "flagless" argument.


These are just my observations of the most common behaviour or CLI tools and I think it makes sense.
