### ISSUE TITLE
Error if default config file doesn't exist

### ISSUE THREAD

**Issue by skeate** [bcoe/yargs#172]
I have a config option, with a default value, but that means that it will always try to read that file, even if it doesn't exist (and if it doesn't, it throws an exception).

Might be nice to have a way to have a default config filename, but not error out if it doesn't exist. It'd be especially slick to *still* error if they specify something with `--config` (or whatever) and **that** file doesn't exist.

**Comment by bcoe** [comment]
@skeate this seems like a good improvement to configuration file management +1.

**Comment by bcoe** [comment]
@skeate if you don't mind, give this branch a shot:

https://github.com/bcoe/yargs/pull/197

I think it's a good solution to your problem, and I could use the help QAing.

**Comment by skeate** [comment]
Looks good to me!

**Comment by bcoe** [comment]
@skeate if you install `yargs@3.15.0`, this should now be fixed.
