### ISSUE TITLE
Require a valid command

### ISSUE THREAD

**Issue by DominicBarnard** [bcoe/yargs#174]
I've been trying to figure out a clean way to require that a valid command argument has been supplied.
Currently I'm using the `check()` method like this:
```js
    .command('command1', 'A command' ,function(){
        // handler...
    })
    .command('command2', 'Another command' ,function(){
        // handler...
    })
    .demand(1, 'must provide a valid command')
    .check(function(argv, opts){
        if(!argv._[0].match(/command1|command2/)) {
            throw new Error('must provide a valid command');
        }
    })
```
This works just fine except any new command that is added in future also has to be remembered to be added to the regex.
I think it would be great to have a cleaner way to specify this behaviour.  Maybe something like a  `requireCommand` method or some option that can be passed to the `strict` method like:
```js
.strict({requireCommand: true})
```

**Comment by bcoe** [comment]
@DominicBarnard I really like this idea. Would you like to take a crack at adding this, I could also look at working on it later in the week.

**Comment by DominicBarnard** [comment]
@bcoe Sure. I'll try to make time for it this week.

**Comment by mahnunchik** [comment]
+1

**Comment by vjpr** [comment]
+1

**Comment by paazmaya** [comment]
:+1: with :grapes:

**Comment by jkwuc89** [comment]
Would like to see this enhancement added as well. In the meantime, @DominicBarnard suggestion above using .check is a decent workaround.

**Comment by nfantone** [comment]
+1 on this. Nice to have.

**Comment by bcoe** [comment]
@DominicBarnard @nfantone @jkwuc89 @paazmaya see:

https://github.com/bcoe/yargs/pull/357
https://github.com/bcoe/yargs/pull/368

This will be landing in `yargs 4`.

**Comment by bcoe** [comment]
@DominicBarnard, @nfantone, @jkwuc89, yargs 4.x now has support for _strict arguments:_

https://github.com/bcoe/yargs/blob/4.x/test/validation.js#L73

Give it a spin by running:

`npm i yargs@next`
