### ISSUE TITLE
Option completion doesn't work with strict arg parsing

### ISSUE THREAD

**Issue by tschaub** [bcoe/yargs#177]
If `strict()` is called, completion of options generates errors.  Here's an example `test.js` script:

```js
#!/usr/bin/env node
require('yargs').completion('completion').help('help').strict().argv;
```

I can enable completion with this:
```bash
$ eval "$( ./test.js completion )"
```

Then if I try to complete the `--help` option after typing `--h[TAB]`, things fail:
```
$ ./test.js --hCommands:
  completion  generate bash completion script

Options:
  --help  Show help  [boolean]

Unknown argument: h
```

This makes sense, given that this is what is being called:
```
./test.js --get-yargs-completions ./test.js --h
```

**Comment by tschaub** [comment]
Perhaps this will work: https://github.com/bcoe/yargs/compare/master...tschaub:completion

**Comment by bcoe** [comment]
Could you take a look at this branch:

https://github.com/bcoe/yargs/pull/181

And see if it does the trick for you?

**Comment by tschaub** [comment]
#181 looks like a good fix for this @bcoe.  Thanks for tackling that.

**Comment by bcoe** [comment]
@tschaub no problem, I'm excited to have another set of eyes on completion -- I'm pretty sure I'm one of the few people who's played with it.

I'm at a conference and am about to run out of battery, but once I'm back at the hotel I will get the patches merged, and will publish a release candidate:

`npm install yargs@next`

 If that that tag seems stable, I'll promote I'll cut a release tomorrow:

`npm install yargs`.

I'll update this ticket once I do so :+1: thanks for the code reviews!

**Comment by bcoe** [comment]
I've pulled all the completion related changes into master and published  them as, `yargs@next`.

If you have a sec give it one final smoke test:

`npm install yargs@next`

If everything seems sane, I'll publish to `latest` tomorrow.
