### ISSUE TITLE
Infinite completion loop

### ISSUE THREAD

**Issue by tschaub** [bcoe/yargs#179]
Given this `test.js` script:
```
#!/usr/bin/env node
var argv = require('./index')
  .completion('completion')
  .argv;

console.log('argv: %j', argv);
```

Enabling completion:

```bash
$ eval "$( ./test.js completion )"
```

And typing `./test.js [TAB][TAB]`, it looks like you get stuck in an endless completion loop with this shown:
```
./test.js completion 
```

You need to send `SIGINT`to get back to sanity (or just watch the endless `-bash: fork: Resource temporarily unavailable`).

**Comment by bcoe** [comment]
@tschaub could you please give this branch a shot and let me know if it solves the problem:

https://github.com/bcoe/yargs/pull/181

**Comment by tschaub** [comment]
Yup @bcoe - the changes in #181 look like a good fix for this as well.

**Comment by bcoe** [comment]
awesome :+1:
