### ISSUE TITLE
Setting a `default()` for `config()` causes an error on `--help`

### ISSUE THREAD

**Issue by rdmurphy** [bcoe/yargs#184]
```js
var argv = yargs.usage('Usage: $0 [options]')
  .config('c').alias('c', 'config').default('config', 'config.json')
  .help('h').alias('h', 'help').argv;
```
When someone tries to run `command --help`, `yargs` throws an error because `config.json` isn't found. But that feels not ideal. My expectation was that it'd print the help text as normal.

Is there something I'm missing?

Thanks!

**Comment by bcoe** [comment]
@rdmurphy see: https://github.com/bcoe/yargs/issues/172

I think we need to fix the behavior around config:

* perhaps we should warn if a config is missing rather than throw an error?
* we should not show the warning if `--help` has been passed.

**Comment by bcoe** [comment]
@rdmurphy If you don't mind, could you give this branch a shot:

https://github.com/bcoe/yargs/pull/197

I think it solves your problem for you -- and I can always use the extra help with QA.

**Comment by bcoe** [comment]
@rdmurphy if you install `yargs@3.15.0`, this problem should now be solved for you.

**Comment by rdmurphy** [comment]
Wasn't able to get around to checking this out last weekend, but that's great! Thanks!
