### ISSUE TITLE
Support for hidden commands

### ISSUE THREAD

**Issue by tschaub** [bcoe/yargs#188]
There are cases where it would be nice to hide some commands from the help/usage output.  An example would be setup or post-install work that is not part of the typical user workflow (e.g. `completion`).  The help output becomes less useful when it is diluted with these one-time or setup type commands.

This could be supported by not adding usage for commands with `false` for a description.  E.g.
```js
yargs.command('post-install', false, handler);
```

If someone wanted the `completion` command to not show up in the help doc, this could be made to work:
```js
yargs.completion('completion', false);
```

Only commands that are registered with usage are eligible for completion, so "hidden" commands would not show up as completion candidates.  I think this is consistent with being hidden.

Prior art:
 * [commander's `noHelp`](https://github.com/tj/commander.js/pull/383)
 * [nomnom's `hidden`](https://github.com/harthur/nomnom#hidden)
 * [argparse's `argparse.SUPPRESS`](https://docs.python.org/dev/library/argparse.html#help)

**Comment by bcoe** [comment]
I like the idea of explicitly providing a `false` description, we could continue to have `undefined` default to a default description.

Big :+1: from me.

**Comment by bcoe** [comment]
@tschaub I've published your changes to `yargs@next`:

`npm install yargs@next`

there's a chance I might do a bit of hacking on yargs this weekend too, and will get a release `yargs@latest` out the door sometime Sunday.
