### ISSUE TITLE
using functions for default doesn't allow to change defaultDescription

### ISSUE THREAD

**Issue by kilianc** [bcoe/yargs#194]
This is super ugly ATM because not only it uses `Function.name` which is readonly and forces the developer to use a wrapper function to rename it, but also you can't use parenthesis in the name.

Example:

```js
const moniker_ = require('moniker').choose

let argv = yargs
  .option('id', {
    alias: 'name',
    type: 'string',
    default: function moniker() { return moniker_() } ,
    describe: 'The log stream id'
  })
```

Nasty names_ and wrapper function, when all I wanted is to print `moniker()` there. I used to override `Function.toString()` which is ugly but at least I was able to achieve the desired result.

**Comment by bcoe** [comment]
@kilianc, you are able to change the default description if you use the `.default()` method rather than the `.option()` shorthand:

```js
let argv = yargs
  .option('id', {
    alias: 'name',
    type: 'string',
    describe: 'The log stream id'
  })
  .default('id', require('moniker').choose, 'moniker')
```

Any thoughts, with regards to better syntax -- I like the `.option()` shorthand (and tend to use it myself), but I want to be careful not to overcomplicate the feature ... does it seem reasonable to expect a user to drop down to a method like `.default()` if they need to set complex configuration settings?

**Comment by kilianc** [comment]
probably using a new key `defaultName` if it's a function fixes everything

**Comment by nexdrew** [comment]
See similar request for `defaultDescription` in #140.

**Comment by nexdrew** [comment]
@kilianc `yargs@3.21.0` should take care of this via a `defaultDescription` property defined in the object passed to `option()`:

```js
var argv = require('yargs')
  .option('id', {
    alias: 'name',
    type: 'string',
    default: require('moniker').choose,
    defaultDescription: 'moniker',
    describe: 'The log stream id'
  })
  .argv
```

Please give it a test run and let us know if it satisfies your use case. Thanks!

**Comment by nexdrew** [comment]
Closing based on the addition of `defaultDescription`. If this doesn't satisfy your use-case, please open another issue. Thanks!
