### ISSUE TITLE
dash problems

### ISSUE THREAD

**Issue by boneskull** [bcoe/yargs#198]
I want to use the string `-` as an option.

My setup is this:

```js
    .option('bullet', {
      describe: 'The bullet to use for each item in the generated TOC.',
      type: 'string',
      default: '*'
    })
```

If I run my program with `--bullet '-'` or `--bullet -`, the dash is instead stuffed into the `_` object.

I think this is actually a problem within bash?  The only way to get it to work is to use `--bullet '\-'`, which gives the string result of `\\-`, then use `String.prototype.replace()`.

**Comment by bcoe** [comment]
@boneskull if you use the `nargs` option, to specify that a minimum of one argument should follow `--bullet`:

```js
#!/usr/bin/env node

var argv = require('./')
  .option('bullet', {
    describe: 'The bullet to use for each item in the generated TOC.',
    type: 'string',
    default: '*'
  })
  .nargs('bullet', 1)
  .argv

console.log(argv)
```

This will behave like so:

```shell
$ ./test.js --bullet '-'

{ _: [], bullet: '-', '$0': 'test.js' }
```

Does this do the trick for you?

**Comment by nexdrew** [comment]
@boneskull Any feedback? Ok to close this issue?

**Comment by boneskull** [comment]
I'll give that a shot; go ahead and close and I'll comment here later if it isn't working for me.  thanks!

**Comment by boneskull** [comment]
err I can close I guess.
