### ISSUE TITLE
Please allow usage strings to be customized and/or formatted.

### ISSUE THREAD

**Issue by waynebloss** [bcoe/yargs#199]
Hi and thanks for your work. One feature I would like to request is to allow the developer to supply the usage strings instead of using the hard-coded "Commands:" and "Options:".

Alternatively, it would be nice to just be able to configure yargs to add one newline after each of those strings so that the usage output isn't formatted so tightly.

**Comment by bcoe** [comment]
@waynebloss I like this idea, I think it would be good to make every string customizable so that we can make strides towards internationalizing yargs. I'll put some thought into what the API would look like for this on the weekend; I'd like to make strings customizable without complicating the API significantly -- how would you feel about setting all of interface's strings in a single configuration step?

**Comment by waynebloss** [comment]
@bcoe Yarg! A single configuration step sounds good. I think all of the [i18n](npmjs.com/package/i18n) modules I've seen for Node store their strings in a single dictionary/key-value style object which is usually "flat" by default, but can also be nested.

Here's a flat example:

```javascript
yargs.swabTheDeckMatey({
  commandsHeader: 'Commands:',
  optionsHeader: 'Options:',
  otherStuff: 'Value'
})...
```

And the nested one:

```javascript
yargs.swabTheDeckMatey({
  header: {
    commands: 'Commands:',
    options: 'Options:'
  },
  otherStuff: 'Value'
})...
```

The i18n npm package is pretty handy and it will do both - not saying to use it because you probably don't need all that functionality, but it might be good to take a look at.

**Comment by waynebloss** [comment]
Here's the gist of the flat/nested conversation that is probably better illustrated - https://www.npmjs.com/package/i18n#object-notation

**Comment by bcoe** [comment]
@waynebloss awesome, would love to hack on this on the weekend. Keep this thread updated with any thoughts you have.

**Comment by bcoe** [comment]
@waynebloss could you take a look at https://github.com/bcoe/yargs/pull/210 and try out the branch, I finally got a chance to tackle this issue.

**Comment by waynebloss** [comment]
@bcoe Hello, I will set a reminder to do that near the end of the week or maybe Saturday.

**Comment by bcoe** [comment]
@waynebloss I've released this functionality on the `next` tag of yargs on npm:

`npm install yargs@next`

**Comment by nexdrew** [comment]
As of yargs v3.18.0, all usage strings and error messages are customizable via [`updateStrings()`](https://www.npmjs.com/package/yargs#updatestrings-obj). The strings to customize are modeled in [en.json](https://github.com/bcoe/yargs/blob/master/locales/en.json).

Also note that yargs now supports multiple locales via the [`locale()`](https://www.npmjs.com/package/yargs#locale-locale) method. If using `locale()` and `updateStrings()` together, you should call `locale()` first.

yargs uses [y18n](https://www.npmjs.com/package/y18n) for localization under-the-hood. If you want to support multiple languages for your own CLI descriptions, y18n is a lightweight alternative to [i18n](https://www.npmjs.com/package/i18n) with a similar API.

If you want more fine-grained control over usage strings that are defined by yargs, take a look at [yargonaut](https://www.npmjs.com/package/yargonaut) (particularly the [`ocd()`](https://www.npmjs.com/package/yargonaut#ocd-fn) method).

Hopefully that satisfies the desired use case. :grinning: If not, please open another issue. Thanks!
