### ISSUE TITLE
Feature request: Support file arguments

### ISSUE THREAD

**Issue by martinheidegger** [bcoe/yargs#2]
Support using minmatch file matchers like **/* to result in a special object that offers to get all file paths or all streams for fast processing.

```
var argv = require("yargs").files("in")

argv.in.pathNames(); // Array of relative path names
argv.in.streams(); // Array of streams
argv.in.streamMap(); // Object with path -> stream map
```

**Comment by bcoe** [comment]
@martinheidegger I like the idea of supporting globs, but the major problem I see is that most unixy shells already glob automatically. It seems like it would be a weird constraint to ask users to wrap filenames in quotes.

With regards to `streams`, vs. ,`pathNames`, vs.,  `streamMap`., I wonder if it's better that this logic live in the application itself. Perhaps we could add documentation that demonstrates how easy it is to get a collection of streams:

```js
argv.in.map(function(path) {
  return fs.createReadStream(path);
});
```

**Comment by bcoe** [comment]
As much as I like this idea, I think there's no elegant way to implement the feature -- since unixy systems already auto-complete globs.

I'm closing this, but would entertain suggestions in the future, as to elegantly implement the feature.
