### ISSUE TITLE
Incorrect value for long strings/integers?

### ISSUE THREAD

**Issue by gullyfoyle** [bcoe/yargs#200]
I have a very simple node script called `parse.js`:

```js
var argv = require('yargs').argv;

console.log('* ' + argv._[0]);
```

When I run it from the command-line (Windows) ...

```> node parse.js 76561197994888976```

It's output is:

```* 76561197994888980```

As you can see, it's a few digits out. Could someone please explain why this is happening?

**Comment by bcoe** [comment]
@gullyfoyle `76561197994888976` is larger than V8's `Number.MAX_SAFE_INTEGER`:

```shell
> Number.MAX_SAFE_INTEGER
9007199254740991
> 76561197994888976 > Number.MAX_SAFE_INTEGER
true
```

Integers larger than this value begin to lose procession. One option would be accepting this value as a string:

```js
var argv = require('yargs')
  .option('foo', {
    type: 'string'
  })
 ```

and then using a module like https://www.npmjs.com/package/big-integer for performing numeric operations.

**Comment by gullyfoyle** [comment]
Thank you so much. I knew it was probably something simple on my part.
