### ISSUE TITLE
Nested commands are treated as a flat structure

### ISSUE THREAD

**Issue by ggoodman** [bcoe/yargs#202]
Given the following command hierarchy and `argv`, `create` will be invoked instead of triggering `check` on the `profile` handler:

```
$0
    create
    profile
        ls
        rm
        ... (no 'create' at this level)
```

ARGV: `['profile', 'create']`.

This is because yargs does not store the nested nature of commands and instead maintains them in a flat hash. Although `profile create` is an invalid command, because both `profile` and `create` each exist, the incorrect command will be invoked.

See: https://github.com/bcoe/yargs/blob/master/index.js#L434

There doesn't seem to be an easy solution to this problem since yargs doesn't maintain any state at the initialization stage as to the relationship between commands. The only case in which this becomes a problem is when a command is defined at a level above the 'category' in which the sub-command is invoked.

What do you think?

**Comment by orlade** [comment]
I have this issue too. Even if `create` does exist at the lower level, yargs will invoke whichever `create` command was registered first. For example:

```
yargs
  .command('create', 'outer', () => console.log('outer create'))
  .command('profile', 'subcommand', (yargs) => {
    yargs.command('create', 'inner', () => console.log('inner create'));
  }).argv;
```

Whether you run `$0 create` or `$0 profile create`, it will print `outer create`.

**Comment by bcoe** [comment]
@ggoodman @orlade we've been working on a pretty major overhaul to commands for `yargs 4`, do you think that named positional arguments would solve your use-case?

see:

https://github.com/bcoe/yargs/pull/368

**Comment by ggoodman** [comment]
I've since moved to `argparse` and adapted the declarative style from `nested-yargs` to that approach.

I think named positionals are an important step in the right direction.

**Comment by TimNZ** [comment]
Can we please have more complex/complete examples for more recent features.  
It's not clear how what the approach is for achieving nested commands e.g. 'npm' style
