### ISSUE TITLE
What about setting «is opt accept value or not»

### ISSUE THREAD

**Issue by a-x-** [bcoe/yargs#212]
Now i must insert `--` between opts and some arg vithout corresponding option
e.g.: `css2stylus --unPrefix -f -- tmp.css`

In time, where classic gnu getopt has this setting:
e.g.: `getopt 'sivp:u'`, where p is marked as accepted value

Thank you and excuse my beginner's English!

**Comment by nexdrew** [comment]
Note that [css2stylus](https://www.npmjs.com/package/css2stylus) is using an older version of yargs ([version 1.2.2 to be precise](https://github.com/dciccale/css2stylus.js/blob/master/package.json#L37)), which did not allow you to configure an argument to be parsed as a boolean, resulting in greedy value slurping.

As of yargs version 3.5.2, you can do something like (notice the use of `boolean()`):

```js
var argv = require('yargs')
  .describe('u', 'Un-prefix any property with vendor prefixes.')
  .alias('u', 'unPrefix')
  .boolean('u')
  .describe('f', 'Overwrite existing .styl files')
  .alias('f', 'force')
  .boolean('f') // THIS FIXES IT
  .argv

console.dir(argv)
```

Which would produce this result:

```sh
$ node example.js --unPrefix -f tmp.css
{ _: [ 'tmp.css' ],
  f: true,
  force: true,
  unPrefix: true,
  u: true,
  '$0': 'index2.js' }
```

Please open an issue (or possibly a pull request) on [css2stylus.js](https://github.com/dciccale/css2stylus.js/issues) to upgrade its yargs dependency to the latest version.

**Comment by a-x-** [comment]
Wow, thank you!
This works, as expected.
