### ISSUE TITLE
help yargs go international!

### ISSUE THREAD

**Issue by bcoe** [bcoe/yargs#214]
Do you speak a language fluently other than English, yargs would love your help translating the CLI. It's easy:

1. [open an issue](https://github.com/bcoe/yargs/issues/new) outlining the language you're adding, this way other people can help with the translation.

2. use [en.json](https://github.com/bcoe/yargs/blob/master/locales/en.json) as a model for your translations:
  * english strings on the left, translations on the right:

    ```json
    {
      "Commands:": "Choose yer command:"
    }
    ```

3. open a pull request with the new locale.

The community's help is greatly appreciated.

**Comment by LoicMahieu** [comment]
Started to working on french : https://github.com/bcoe/yargs/pull/215

**Comment by bcoe** [comment]
@LoicMahieu very much appreciated thank you!

**Comment by bcoe** [comment]
We now have French released in `yargs@3.17.1`, thanks @LoicMahieu.

**Comment by bcoe** [comment]
@zkat is working on Spanish: https://github.com/bcoe/yargs/pull/220

**Comment by bcoe** [comment]
@codemonkey3045 is working on Portuguese \o/ https://github.com/bcoe/yargs/pull/224

**Comment by bcoe** [comment]
we have a pretty great selection of languages now, closing this ticket and considering it a success. Thanks everyone :rainbow:
