### ISSUE TITLE
multiple commands

### ISSUE THREAD

**Issue by jmls** [bcoe/yargs#225]
so, I'm pretty sure that this can be done, but for some reason I am struggling

what I want to have is

```javascript
myapp create project [options]
myapp create module[options]
myapp list [options]
```
etc

so, if the user enters just "myapp" I want to show

```javascript
usage: myapp <command>
commands:
  create : create a new [project|module]
  list : list items in project
```
if the user enters "myapp create"

```javascript
usage: myapp create <item> [options]
item:
  project : create a new project
  module : create a new module
```

at this point I can do the defaults / required for [options] for each particular command

what am I missing ?

**Comment by nexdrew** [comment]
Here's an adaptation from [the `command()` docs](https://www.npmjs.com/package/yargs#command-cmd-desc-fn) that should help get you started:

```js
var yargs = require('yargs')
var argv = yargs
  .usage('usage: $0 <command>')
  .command('create', 'create a new [project|module]', function (yargs) {
    argv = yargs
      .usage('usage: $0 create <item> [options]')
      .command('project', 'create a new project', function (yargs) {
        console.log('creating project :)')
      })
      .command('module', 'create a new module', function (yargs) {
        console.log('creating module :)')
      })
      .help('help')
      .updateStrings({
        'Commands:': 'item:'
      })
      .wrap(null)
      .argv
    checkCommands(yargs, argv, 2)
  })
  .command('list', 'list items in project', function (yargs) {
    console.log('listing projects :)')
  })
  .help('help')
  .wrap(null)
  .argv

checkCommands(yargs, argv, 1)

function checkCommands (yargs, argv, numRequired) {
  if (argv._.length < numRequired) {
    yargs.showHelp()
  } else {
    // check for unknown command
  }
}
```

---

```
$ myapp 
usage: myapp <command>

Commands:
  create  create a new [project|module]
  list    list items in project

Options:
  --help  Show help  [boolean]
```

```
$ myapp create
usage: myapp create <item> [options]

item:
  project  create a new project
  module   create a new module

Options:
  --help  Show help  [boolean]
```

```
$ myapp create project
creating project :)
```

```
$ myapp create module
creating module :)
```

```
$ myapp list
listing projects :)
```

Good luck, and thanks for using yargs!

**Comment by bcoe** [comment]
@nexdrew also see #202, I'd like to find a way to make commands a bit more intuitive -- without complicating the API too much (convention vs. configuration).

**Comment by nexdrew** [comment]
Hmm. Of the few CLI libs I've looked at ([commander](https://www.npmjs.com/package/commander), [nomnom](https://www.npmjs.com/package/nomnom), [meow](https://www.npmjs.com/package/meow), [optionator](https://www.npmjs.com/package/optionator)), only commander seems to have support for subcommands built into the API, and it's based on using separate executable files that each have their own full commander config.

I think the most intuitive thing would be to define config for any given command as an object literal, and then you could easily nest subcommand objects within a parent command object.

E.g. let's say we supported this command object syntax:

```js
.command({
  cmd: 'list', // name
  desc: 'list items in project', // description
  fn: function (yargs) { console.log('listing items in project') }
})
```

Then perhaps they could be nested like this:

```js
.command({
  cmd: 'create',
  desc: 'create a new item',
  subcommands: [
    {
      cmd: 'project',
      desc: 'create a new project',
      fn: function (yargs) { console.log('creating project') }
    },
    {
      cmd: 'module',
      desc: 'create a new module thing',
      subcommands: [
        {
          cmd: 'config',
          desc: 'module configuration',
          fn: function (yargs) { console.log('creating module configuration') }
        },
        {
          //...
        }
      ]
    }
  ]
})
```

Would be nice if yargs could then handle the help content context switch automatically. This could also lead to supporting other command niceties in the future, like [command aliases](https://github.com/bcoe/yargs/issues/121).

I don't know, just kinda thinking out loud here. Not sure if that would complicate the API/usage/parsing too much, or if it satisfies "convention over configuration". Just trying to get the creative juices flowing a little bit.

**Comment by danielvy** [comment]
The object notation makes a lot of sense but I think it's missing an important element.

More often than not "command" doesn't just mean *'if you see thing string, do this'* (although sometimes it does) but rather *'now the application expects the user to tell it what to do via one or more actions'*.

So *create* and *delete* are both actions of a "command" but defining them as separate `command(...)` objects doesn't make sense. They may have some elements in common (e.g both may require a project name) but they also have different help strings, their own options (on top of global ones) and are mutually exclusive.

I think that the API should somehow reflect this. Either by moving the `.command()` notation one level higher (logically) and make it have a list of action objects. Or, allow it to accept an array of "command" objects and a common options object.

I am not an expert, just trying to apply my experience as CLI user to some thoughts on the matter.

**Comment by bcoe** [comment]
I like the idea of command optionally taking an object, and allowing for sub commands to be defined here -- it starts to solve the order of operation problem discussed here:

https://github.com/bcoe/yargs/issues/202

Here's a thought, what if we introduce a configuration option for options called `global`, this would indicate that the option should not be reset when in the context of a commands' handler. We could default options like help, and version to `global`.

Thoughts?

**Comment by davidcl64** [comment]
I've taken a convention over configuration approach to this in one of my projects.  

As an example - given a directory structure that looks something like this:

    +- cli.js
    +- commands
        +- create_commands
        |   +- project.js
        |   +- module.js
        +- create.js
        +- list.js   

Each module needs to export a description and, in the case of the sub-commands, a command function that will be invoked by yargs.

For example:

create.js - top level command with sub-commands so only needs a description.

    module.exports.description = 'create a new project';

list.js - top level command that is invoked on its own:

    module.exports.description = 'list items in project';
    module.exports.command = function (yargs) {
      console.log('listing items in project :)')
    })

project.js & module.js are implemented in a similar fashion to list.js.

This script then loads everything up:

    var path       = require('path');
    var requireAll = require('require-all');
    var package    = require('../package.json');
    var commands   = requireAll(path.join(__dirname, 'commands'));
    
    var yargs = require('yargs');
    
    function loadCommands(yargs, commands, level, parent) {
      level  = level || 1;
      parent = parent ? ' ' + parent : '';
    
      yargs
        .demand(level)
        .usage('Usage: $0' + parent + ' <command> [options]');
    
      Object.keys(commands).forEach(function (commandName) {
        var isFolder, subCommands;
    
        commandName = commandName.split('_');
        isFolder  = commandName[1];
        commandName = commandName[0];
    
        if(isFolder) { return; }
    
        subCommands = commands[commandName + '_commands'];
        if(!subCommands) {
          yargs = yargs.command(
            commandName,
            commands[commandName].description,
            commands[commandName].command
          );
        } else {
          yargs = yargs.command(
            commandName,
            commands[commandName].description,
            function(yargs) {
              loadCommands(yargs, subCommands, level + 1, commandName);
            }
          )
        }
      });
    
      yargs.help('help');
    }
    
    loadCommands(yargs, commands);
    yargs.argv;
    
There's a couple of hacks in there (level & parent for example), but this works reasonably well for my purposes.

**Comment by H3Chief** [comment]
Why not just use `[.reset()](https://github.com/bcoe/yargs#reset)`?

**Comment by H3Chief** [comment]
yeah... so reset doesn't actually seem to work at all in the way described. Neither does any of the nesting.

**Comment by bcoe** [comment]
@H3Chief I would like to overhaul the commands functionality, I think this will be the motivation for `yargs@4.x`, If I have a bit of time this weekend I'll try to finally put together a proposal.

**Comment by H3Chief** [comment]
Let me know if you want any help. I've been kicking this around the last few days myself and was looking to work on a solution this weekend anyways.

**Comment by stelcheck** [comment]
I found two issues in yargs that would need to be fixed for multiple commands to be properly handled:

## Nested command orders

Based on the previous example, suppose you have:

```bash
myapp create [options]
myapp module create [options]
myapp list [options]
```

`myapp module create` will actually execute `myapp create` instead. The patch I will submit shortly takes care of this case by tracking the nesting level.

## Incorrect nested command

Also based on the sample, if I try `myapp invalid`, I do not get an error. For this last one, I am expecting there is a way to handle this case, but I just don't know which it is (suggestions welcome).

## About API improvements

Some have suggested to provide a nicer API for such usage. Personally, I am fine with the current API.

**Comment by bcoe** [comment]
@jmls @stelcheck see:

https://github.com/bcoe/yargs/pull/368

We've overhauled commands for `yargs 4`, in an attempt to address the shortcomings of the current API:

* there are now named positional arguments (which helps solve many of the nesting issues folks were running into).
* you can now provide commands as modules (which should help people build significantly more complex APIs on top of yargs).

**Comment by AGresvig** [comment]
I'm digging the overhaul of `commands` in 4.x, but it's still not entirely clear to me how support for sub-commands should be implemented if the type of behavior outlined by @jmls initially here is desired. 

Specifiying a command like so:
`.command('resources <operation> [option]',..)` still parses `operation` as a flag, not a command.

Should I adopt a variation of nesting `command`s as initially suggested by @nexdrew?

**Comment by jdc0589** [comment]
@AGresvig no idea if this is how its "supposed" to works as a starting point:

```js
var yargs = require("yargs");

var argv = yargs.usage("$0 command")
	.command("foo", "top level command", function(yargs) {
		return yargs
			.command("bar", "child command of foo", function() {
				console.log("barr!");
			});
	})
	.demand(1, "must provide a valid command")
	.help("h")
	.alias("h", "help")
	.argv
```

produces: 

```shell
▶ node index.js -h
index.js command

Commands:
  foo  top level command

Options:
  -h, --help  Show help                                                [boolean]
```

and: 

```shell
▶ node index.js foo -h
index.js foo

Commands:
  bar  child command of foo

Options:
  -h, --help  Show help                                                [boolean]
```

**Comment by vjpr** [comment]
Just wanted to add this here to clarify the example above. To access the `argv` of the sub-command including named arguments you need to pass a fourth argument to command.

```
yargs
  .command(
    'get',
    'make a get HTTP request',
    function (yargs) {
      return yargs.option('u', {
        alias: 'url',
        describe: 'the URL to make an HTTP request to'
      })
    },
    function (argv) {
      console.log(argv.url)
    }
  )
  .help()
  .argv
```

**Comment by AGresvig** [comment]
Thanks @jdc0589 - this seems to work but quickly leads to nasty nesting. There should be a way to do this with a flatter structure - ideally using [positional arguments](http://yargs.js.org/docs/#methods-commandmodule-positional-arguments)..

@vjpr for providing examples. I know see how to access `argv` using commands. 

But I think this issue highlights the ambiguity surrounding sub-commands. It is still not clear to me - nor does it seem to be clear to others - how exactly one should achieve ***sub***-*command*  functionality with clear code and sensible help features.

I am looking for the same type of behaviour as requested in the OP, i.e. `myapp create project [options]`

If anyone could show me how to achieve this with commands I'd be very happy!

**Comment by nexdrew** [comment]
@AGresvig This is something I plan to address with #494 using modules for subcommands and a simple directory structure to facilitate nesting. Feedback is welcomed.

**Comment by AGresvig** [comment]
@nexdrew Ah fantastic, I had missed this. It looks to be very aligned with what I had in mind. Thanks! 
I'll review it.

**Comment by moranje** [comment]
Quick question: Is the entire API supported under `exports.<method>`? Would I be able to use `completion`, `demand`, `example` etc. methods on the exports method for instance? I't not entirely clear from the docs. Another thought, do you think `desc` might be better written in full (`description`) to mirror the API?

**Comment by nexdrew** [comment]
@moranje The entire API is not available via _exports_, but it _is_ available to the `builder` function, since it's given a full yargs instance. So you can apply `.completion()`, `.demand()`, `.example()`, et al to your command that way. Just make sure to return the yargs instance (and note that `.demand()` should currently be a number that includes the command arg itself).

For the command description, you can actually export `description`, `describe`, or `desc` - they are all supported.

**Comment by moranje** [comment]
That makes sense, thanks for clarifying that.

**Comment by cemtopkaya** [comment]
require("yargs").usage("$0 command")
    .command({
        command: "foo",
        description: "top level command",
        builder: {
            command: "bar",
            description: "child command of foo",
            builder: function() {
                console.log("builder barr!");
            },
            handler: a => {
                console.log("handler barr!");
            }
        },
        handler: args => {
            console.log("handler foo!");
        }
    })
    .demand(1, "must provide a valid command")
    .help("h")
    .alias("h", "help")
    .argv

![image](https://user-images.githubusercontent.com/261946/94349123-4e874580-004a-11eb-92e1-f3fb4707c0fe.png)

**Comment by Sawtaytoes** [comment]
The value of @cemtopkaya's post is incredible!

Thank you so much for making this much simpler. Now I can include `yargs` functions in other files and have `builder` manage them.

I'm curious, is there a trick to combining multiple sub-builder functions if you have more than one?
