### ISSUE TITLE
Setting Up yargs.js.org

### ISSUE THREAD

**Issue by blainsmith** [bcoe/yargs#232]
Here is the hit list to get this done.

- [x] You create a `gh-pages` branch I can submit a pull request to
- [x] I get that Flatdoc site set up
- [x] You submit a PR to https://github.com/js-org/dns.js.org to add `yargs.js.org` to `cnames_active.js`
- [x] Rejoice!

**Comment by bcoe** [comment]
awesome, I will get on this tomorrow.

**Comment by bcoe** [comment]
@blainsmith alright, `gh-pages` branch is a thing.

**Comment by nexdrew** [comment]
This looks fun. Let me see if I can prep the `gh-pages` branch a bit.

**Comment by nexdrew** [comment]
I recreated the `gh-pages` branch and setup the basic Flatdoc template.

http://bcoe.github.io/yargs/

Would be cool to customize the default theme. Not sure what you had in mind @blainsmith, but this should get us going. Thanks!

**Comment by bcoe** [comment]
\o/ 
![no-idea](https://cloud.githubusercontent.com/assets/194609/9364343/b59ea186-4660-11e5-8ef5-a3da3ce16ba6.jpg)

**Comment by nexdrew** [comment]
LOL! Think I just have too much time on my hands. :laughing:

**Comment by blainsmith** [comment]
Nice! Glad it was such a piece of :cake:  to do.

**Comment by nexdrew** [comment]
@blainsmith Your todo list made it easy. Thanks a lot!

If anyone has ideas for how to customize the Flatdoc site, I'm all ears (and PRs are welcomed)!

**Comment by blainsmith** [comment]
Should be as simple as adding your own stylesheet with overrides.

**Comment by nexdrew** [comment]
@blainsmith Thanks again!

**Comment by blainsmith** [comment]
Anytime!
