### ISSUE TITLE
Requiring doesn't work anymore

### ISSUE THREAD

**Issue by maxrimue** [bcoe/yargs#236]
I created a node module and built in yargs to check for commands and flags etc.
I made yargs require at least one command, and each command requires certain options.
Using my module via the CLI works just fine and as expected, however, when I want to require my module for programmatic use, I get an error that at least one command is required. So the problem here is that my module now responds to a require() like to a call from the CLI. Is that supposed to happen?

**Comment by nexdrew** [comment]
How have you structured your module? For CLI modules that can also be used as a library, you would typically put your core library code in `index.js`, which would be your `main` file in `package.json`, and you would put your CLI code (that requires `index.js`) in an executable file like `cli.js`, which would be a `bin` file in `package.json`.

Something like this:

#### package.json

```json
{
  "name": "mymodule",
  "main": "index.js",
  "bin": {
    "mymodule": "cli.js"
  },
  "dependencies": {
    "yargs": "^3.19.0"
  }
}
```

#### index.js

```js
module.exports = function () {
  console.log('this is mymodule')
}
```

#### cli.js

```js
#!/usr/bin/env node
var mymodule = require('./index.js')
var argv = require('yargs').argv
//...
mymodule()
```

Then other modules can `require('mymodule')` and the CLI portion will be ignored. Does this not work?

**Comment by maxrimue** [comment]
@nexdrew Thanks a lot! This solves it. It was actually my first global module, so I wasn't familiar with that concept, I tried to put both into one file. Thanks!

**Comment by nexdrew** [comment]
No problem, good luck! :smiley_cat:
