### ISSUE TITLE
Completion in ZSH ala https://github.com/bcoe/yargs/pull/118

### ISSUE THREAD

**Issue by jameswomack** [bcoe/yargs#252]
Has this been discussed @bcoe ?

**Comment by bcoe** [comment]
@jameswomack I would love to add ZSH support, but when implementing things only put the time in for bash -- don't suppose you'd be interested in taking a stab at it.

CC: @nexdrew don't suppose you use ZSH :)

**Comment by jameswomack** [comment]
@bcoe I am interested in it—so far I discovered that ZSH has a Bash Completions compatibility feature, it requires one to call a function in their zshrc and then source the completions file.

**Comment by nexdrew** [comment]
Unfortunately I don't use ZSH either :( I might be able to set up a system that does though.

@jameswomack Do you think Bash compatibility will work for you in the meantime?

**Comment by jameswomack** [comment]
@nexdrew It will definitely work for me as a consumer of libraries based on yargs (i.e. if I install someone else's CLI).

I hope to report back when I play around with installing completions for consumers of *my* libraries written using yargs.
