### ISSUE TITLE
demand does not work with alias

### ISSUE THREAD

**Issue by hajoeichler** [bcoe/yargs#255]
Hi,

I have defined:
```
# CoffeeScript:
yargs
.describe 'p', 'project'
.alias 'p', 'project'
.demand 'p'
```
When I call the program with `--project` then I get the following output (which is the same if I run the command without any arguments:
```
Missing required argument: p
```
With `-p` the program works as expected.

**Comment by bcoe** [comment]
@hajoeichler I'm a bit confused, I just tested this on `yargs@3.24.0` and things worked appropriately:

```js
#!/usr/bin/env node

var yargs  = require('./')
  .describe('p', 'project')
  .alias('p', 'project')
  .demand('p'),
  argv = yargs.argv

console.log(argv)
```

```shell
./test.js 
Options:
  -p, --project  project                                              [required]

Missing required argument: p
```

```shell
./test.js -p foo
{ _: [], p: 'foo', project: 'foo', '$0': 'test.js' }
```

```shell
./test.js --project foo
{ _: [], project: 'foo', p: 'foo', '$0': 'test.js' }
```

**Comment by nexdrew** [comment]
I concur with @bcoe. Even my tests using `yargs@3.15.0` (same version used by `sphereio/sphere-category-sync`) exhibit the behavior described by @bcoe. I think we need a test case that more closely matches how `yargs` is being used by `sphereio/sphere-category-sync` in order to reproduce the problem.

**Comment by hajoeichler** [comment]
@bcoe and @nexdrew thanks for your fast answers. I am currently trying to reproduce the problem myself - seems to be a wild combination of things necessary. Please hang tied.

**Comment by hajoeichler** [comment]
Sorry, can't reproduce it any longer.
In the middle of investigating I thought it was related to the hyphen in the parameter `--project-key`, but also this one I can reproduce.

Thanks for the feedback anyway.

**Comment by nexdrew** [comment]
@hajoeichler Ok to close then?
