### ISSUE TITLE
.count misbehaves with hyphenated flags

### ISSUE THREAD

**Issue by kahlil** [bcoe/yargs#256]
If I do something like this: 
```js
var opts = require('yargs')
    .count('log-level')
    .alias('l', 'log-level')
    .argv;

console.log(opts);
```
And pass `-lll` yargs will always count 2 no matter what. If I use `loglevel` as the main name of the flag it counts them correctly.

**Comment by bcoe** [comment]
Hey @kahlil what version of yargs are you running, I can't seem to reproduce:

```js
#!/usr/bin/env node

var opts = require('./')
    .count('log-level')
    .alias('l', 'log-level')
    .argv;

console.log(opts);
```

```shell
Benjamins-MacBook-Pro:yargs benjamincoe$ ./test.js -llll
{ _: [], l: 4, 'log-level': 4, logLevel: 4, '$0': 'test.js' }
```

**Comment by phated** [comment]
Sorry, this is probably related to gulp-cli, which is on a super old version (1.3.3).  I am working on updating it now.

**Comment by phated** [comment]
Ref https://github.com/bcoe/yargs/issues/78

**Comment by kahlil** [comment]
Oops, @phated is right. I did not check the version! Sorry for this 🙏

**Comment by nexdrew** [comment]
Closing based on previous comments. If you find another problem, please open a new issue. Thanks!

**Comment by hildjj** [comment]
With version 3.30.0:

```
var argv = require('yargs')
.options({
  verbose: {
    description: 'Verbose output',
    boolean:     true,
    count:       true,
    alias:       'v'
  }
}).argv;

console.log(argv.verbose);  // outputs 2+count(v)
```

With .options, the count is always 2 more than it should be.  Using:

```
var argv = require('yargs')
    .count('verbose')
    .alias('v', 'verbose')
    .argv;
```

everything seems to work fine.

**Comment by hildjj** [comment]
Actually, it's the `boolean: true` that's causing the issue, not .options.

**Comment by nexdrew** [comment]
@hildjj Thanks for pointing this out! `count` is just a special form of `boolean`, so the `boolean` part is superfluous/unnecessary.

**Comment by hildjj** [comment]
Perhaps a warning/error, then, if you specify both?  Starting the count at 2 was unexpected behavior.

**Comment by nexdrew** [comment]
@hildjj Agreed. Would you mind creating a new ticket for that?
