### ISSUE TITLE
Document the "type" property

### ISSUE THREAD

**Issue by gajus** [bcoe/yargs#262]
I am trying to use the `type` property to restrict option value type. I cannot find documentation/list of the supported types. Using any value (e.g. "foobar") has no effect/produces no error.

```js
.option('force', {
    demand: false,
    describe: 'Write to file with different extension than ".md".',
    type: 'foobar'
})
```

**Comment by nexdrew** [comment]
@gajus Good point, thanks for the suggestion! I think the documentation implies that object properties given to the `option()` method are meant to replace the equivalent chainable methods, but I agree that it's not always intuitive and should be explicitly documented either way.

In the meantime, here are the valid/effective `type` values:

- `'boolean'`
- `'array'`
- `'string'`
- `'count'`

Which are synonymous with defining properties of the same name with a value of `true` (or calling a chainable method of the same name and passing the option key/name as an argument). Just to be clear, these are all equivalent:

```js
.option('force', {
  describe: 'Write to file with different extension than ".md".',
  type: 'boolean'
})
```

```js
.option('force', {
  describe: 'Write to file with different extension than ".md".',
  boolean: true
})
```

```js
.describe('force', 'Write to file with different extension than ".md".')
.boolean('force')
```

Note that there has been [some discussion about adding support for a `'number'` type](https://github.com/bcoe/yargs/issues/110), but this is still TBD.

**Comment by nexdrew** [comment]
@gajus Documentation has been added as of version 3.26.0. Let me know if anything seems unclear. Thanks!
