### ISSUE TITLE
Use array with gulp

### ISSUE THREAD

**Issue by alisabzevari** [bcoe/yargs#264]
I think it is good to have different syntaxes for array form. Using array with gulp throws errors:
```javascript
var argv = require("yargs")
  .array("modules")
  .argv;
```
Using it like this:
```
gulp taskname --modules m1 m2
Task 'm2' is not in your gulpfile
```

**Comment by nexdrew** [comment]
Possible workaround:

```sh
gulp taskname --modules m1 --modules m2
```

**Comment by alisabzevari** [comment]
Thanks it worked for me.

**Comment by nexdrew** [comment]
This might work as well, though I haven't tested it:

```sh
gulp taskname -- --modules m1 m2
```

**Comment by alisabzevari** [comment]
@nexdrew, The second one does not work.

**Comment by OClement** [comment]
Although the first work around works, is there no plan to make this work as intended? 
I can live with this, but is kind of annoying still to have to repeat the flag for each items

**Comment by TheHanna** [comment]
@OClement Agreed. Just started using this in a project, and being able to use the normal array syntax with gulp would be great.

**Comment by JacobDB** [comment]
Anyone figure out how to get this working? I thought for sure I was doing something wrong, but I guess not.

**Comment by TheHanna** [comment]
@JacobDB Unfortunately, I still have not been able to get it to work

**Comment by JacobDB** [comment]
@TheHanna that's unfortunate, maybe when Gulp 4 is officially released it'll work with that.
