### ISSUE TITLE
Arguments are validated if help or version is used and exitProcess=false

### ISSUE THREAD

**Issue by tepez** [bcoe/yargs#272]
Fixed and explained in [PR 271](https://github.com/bcoe/yargs/pull/271).

**Comment by tepez** [comment]
As a workaround, I'm currently overriding `showHelp` and throws an exception after printing the help.

```coffee
try

    origShowHelp = yargs.showHelp
    yargs.showHelp = () ->
        origShowHelp.apply(yargs, arguments)
        throw new Error('showed help')

    argv = yargs.argv

    # other stuff here

catch err
    if err.message == 'showed help'
        # not really an error, so do nothing
        return
       
    # really errors handling
```

**Comment by nexdrew** [comment]
@tepez Thanks again for your contributions! Would you mind giving 3.27.0 a test drive to verify this issue has been fixed? Then we can safely close this out.

**Comment by tepez** [comment]
@nexdrew my pleasure, and thank you for maintaining this great package.
I've just updated to 3.27.0 and all my units tests are passing.
