### ISSUE TITLE
Support grouping of options in help content

### ISSUE THREAD

**Issue by nexdrew** [bcoe/yargs#274]
This is a feature requested by at least a few different folks. See some discussion and ideas in [issue 152 here](https://github.com/bcoe/yargs/issues/152#issuecomment-125863571) and in [issue 260](https://github.com/bcoe/yargs/issues/260).

Personally, I like the API methods that accept the group name/key first, e.g. `.group(groupName, options)`, because I think it's cleaner and more intuitive, but note that this would be a deviation from most other API methods that accept the option key first. I think the deviation is justifiable though. Any options defined without a group would default to the existing yargs-defined pseudo group `'Options:'`, for backwards compatibility.

Another thing to consider is i18n support for consumer-defined strings, which should probably be another separate enhancement, but I think it would be nice to introduce the concept here. Perhaps the group name could be treated as a y18n key that yargs automatically resolves from consumer-defined locale files - similar to yargs-defined keys but resolved from (a `locales` directory in) the parent module. That way, consumers could get the benefit of yargs locale detection and y18n lookup without any additional API/code changes (besides adding their own locale files). This idea could be extended to option and command descriptions as well. Something to think about.

**Comment by Cellule** [comment]
+1
I have been using my own set of groups for sub commands to share common options and how to use them. 
It works pretty well, but the help message is getting out of hand.

**Comment by bcoe** [comment]
@nexdrw I like where you're going with this a lot. A couple comments:

* I think the default behavior should be an API identical to the existing one (you already suggest this). the great thing is that we get the additional grouping functionality, without any breaking changes -- groups such as `Options` simply alias the new named group functionality _love it!_.
* I like your idea that we'd be clever about sourcing keys from `i18n`; going forward, if certain group names become common, we could add these translations to the translation files we ship.

**Comment by bcoe** [comment]
@timmckenzie, @ammeep, @nexdrew yargs now has the new `.group()` command which allows you to split your arguments across multiple categories give it a spin:

`npm i yargs@3.30.0`
