### ISSUE TITLE
completion promise support

### ISSUE THREAD

**Issue by LinusU** [bcoe/yargs#278]
I think it would be great if the `completion` function could accept an promise as well. As it is now, if you want to do something async you need to add an extra `done` parameter.

It could be implemented like this:

```javascript
const ret = completer(...)

if (typeof ret.then === 'function') {
  ret.then(function (value) {
    // use value
  })
} else {
  // use ret
}
```

It would allow it to be used like this with babel:

```javascript
yargs
  .completion('completion', async function (current, argv) {
    const listPromise = findListCompletions(current)
    const installPromise = findInstallCompletions(current)

    const [list, install] = await [listPromise, installPromise]

    return [...list, ...install]
  })
```

Or with plain promises:

```javascript
yargs
  .completion('completion', function (current, argv) {
    const listPromise = findListCompletions(current)
    const installPromise = findInstallCompletions(current)

    return Promise.all([listPromise, installPromise]).then(function (res) {
      return res[0].concat(res[1])
    })
  })
```

**Comment by bcoe** [comment]
@LinusU I like this idea a lot, but I'd love to avoid pulling a promise library into yargs (since we're not using promises elsewhere in the codebase).

Could we detect native promises and return a promise if possible? If we used this approach is it possible for the consuming library to shim native processes with bluebird or q? how would that work.

**Comment by LinusU** [comment]
We wouldn't need to include any library since we would only comsume the promises, not create them :)

Promises can be detected by checking if .then is a function.

**Comment by bcoe** [comment]
@LinusU I like this idea, would you like to take a stab at it?

**Comment by LinusU** [comment]
Sure thing :+1:
