### ISSUE TITLE
Array instead of plain value when default value and alias provided

### ISSUE THREAD

**Issue by mir3z** [bcoe/yargs#279]
Consider the following example:

``` javascript
var argv = require('yargs')
    .option('foo.bar', {
        default: 100,
        alias: 'f'
    })
    .argv;

console.warn(argv.foo.bar);
```

```bash
$ node app.js --foo.bar 200
[ 200, 100 ]
```
For me expected result in this case would be that `argv.foo.bar` is equal to `200`

**Comment by bcoe** [comment]
@mir3z could you give https://github.com/bcoe/yargs/pull/281 a spin, and see if it addresses your parsing issues?
