### ISSUE TITLE
Feature request: automatically generate bash completion

### ISSUE THREAD

**Issue by martinheidegger** [bcoe/yargs#3]
Grunt has a very elegant way to do bash completion, unfortunately it is also very low level.

https://github.com/gruntjs/grunt-cli/tree/master/completion

It would be cool if yargs would have a option to directly get bash code for completion that automatically shows what options are available and might even support lookup.

```
var argv = require("yargs").shellCompetion("auto-complete", { // with optional lookup object to realtime evaluate properties that are system specific ...
   task: function(input) {
     return [...]
  }
})

if(argv["auto-complete"]) {
   console.info(argv.renderAutoComplete());
}
```

**Comment by bcoe** [comment]
So you're picturing something like:

`eval "$(my-program-that-relies-on-yargs --completion=bash)"`

Could you give me an example of some expected inputs and outputs?

**Comment by bcoe** [comment]
@martinheidegger I've taken a first stab at bash-completions, let me know what you think:

https://github.com/bcoe/yargs/pull/118

**Comment by bcoe** [comment]
@martinheidegger I've added completion functionality to yargs, documented here:

https://github.com/bcoe/yargs#completioncmd-description-fn

Give it a shot and let me know what you think, it's on the `next` tag on npm:

`npm install yargs@next`
