### ISSUE TITLE
suggestion: support arbitrary filename for configuration file

### ISSUE THREAD

**Issue by sebastienbarre** [bcoe/yargs#304]
Right now it seems only `.json` files can be used for config files, because they are `require()`'ed. Would be nice to support any filename, such as `.foorc`. Very minor but it took me a bit to figure out why this wasn't working. Thanks.

**Comment by bcoe** [comment]
@sebastienbarre good call. Do you think it would be a good idea to switch back to `JSON.parse()` for loading configuration...

An alternative interesting idea I'd like to float, what if `config` accepted an optional closure for performing the parsing, this would allow you to accept `TOML`, `YAML`, `INI`, etc, without yargs having to be too clever.

CC: @nexdrew

**Comment by sebastienbarre** [comment]
@bcoe actually I thought about it more later on and realized the benefit of using `require` is that you could execute arbitrary code there -- switching to `JSON.parse()` could break backward compatibility. I think this closure idea would be the best of both world, I vote for it.

**Comment by indieisaconcept** [comment]
@bcoe I was looking for similar support but have been able to implement it without needing to change yargs. 

If you omit config('c') from your yards configuration then it is not automatically loaded. This permits you to write your own loader when this arg is supplied. I'm doing this to support .yaml.

**Comment by bcoe** [comment]
@sebastienbarre @indieisaconcept, so my idea was that you'd be able to pass an arbitrary parser to the `.config()` as an additional argument -- what do you think of this solution?

**Comment by indieisaconcept** [comment]
@bcoe that would be in-keeping with the approach for version. I like it.

**Comment by sebastienbarre** [comment]
@bcoe yup, still on board with this, a closure would work :)
