### ISSUE TITLE
Read option values from env vars

### ISSUE THREAD

**Issue by nexdrew** [bcoe/yargs#305]
In the spirit of [the 3rd factor of a 12 factor app](http://12factor.net/config) and to better support services that traditionally pass env var values as CLI options anyway, let's consider supporting the ability to read env vars for values of configured options (and cut out the middleman which usually takes form in a shell script).

## Potential Approaches

1. The Automagical Approach

    With the flip of a configuration switch, `yargs` could automatically take option names, convert them to their env var equivalent, and use those env vars that are defined as values for options that have not been specified on the command line.

    For example, an option like `--foo-bar` could be translated to env vars `FOO_BAR` or `FOOBAR`, with the following results:

    ```
    $ FOO_BAR=x program --foo-bar y
    { _: [], 'foo-bar': 'y', fooBar: 'y', '$0': program' }
    ```

    ```
    $ FOO_BAR=x program
    { _: [], 'foo-bar': 'x', fooBar: 'x', '$0': program' }
    ```

    ```
    $ program
    { _: [], '$0': program', 'foo-bar': undefined }
    ```

    The API could be either a single configuration switch that enables env var lookups for all options (e.g. `yargs.envVars(true)` or could be configured per option (e.g. `yargs.envVar('foo-bar', true)`) or could possibly be enabled for only required options or only non-required options.

    To avoid name clashes with common env vars like `PATH` or `HOME`, the API should support a configurable prefix, e.g. `yargs.envVars('PREFIX_')`.

2. The Explicit Approach

    `yargs` could simply allow an equivalent env var to be explicitly specified per option. If the option is not given on the command line, then `yargs` would then look for the configured env var and use its value if defined.

    For example, an option `--foo-bar` could be explicitly mapped to a `FOO_BAR` env var (or even `SOMETHING_TOTALLY_DIFFERENT`) and the results from above would be the same.

    The API could be as simple as `yargs.envVar('foo-bar', 'FOO_BAR')` or `yargs.option('foo-bar', { envVar: 'FOO_BAR' })`.

3. Some Hybrid of 1 and 2

    The Automagic Approach is much less verbose, making it easy for consumers to build support for env vars without many code changes and without manually specifying a bunch of env var names that will probably be very similar to option names anyway. However, it has the problem of potential name conflicts with env vars not meant for the `yargs` program, requiring a prefix solution or similar. It also has the problem of not allowing overrides on a per-option use-case.

    The Explicit Approach makes for a simple, common API without implicit ambiguity, but it potentially requires a lot of redundant configuration that could be avoided.

    Perhaps we could leverage both, allowing a switch for implicit env var interpretation while also allowing individual options to explicitly override the implicit env var naming. The API could be similar to:
    - `envVars(prefixAsString || boolean || arrayOfOptions || objectMultiConfig)`
    - `envVar(option, envVarNameAsString || arrayOfEnvVarNames)`

## Considerations

1. How to display support for env vars in usage/help text?
2. Disallow or warn on name clashes with common system env vars?
3. How to selectively apply prefix to certain option groups (e.g. required only or non-required only) or only options that need it?
4. How to support short flags with no long name alias?

Feedback or other ideas welcomed.

**Comment by bcoe** [comment]
@nexdrew I really like this idea, for starters I think it would be a great way to cut down on some of the logic we have in our apps at npm -- we seem to gradually be migrating to a highbred approach between environment variables and arguments, it would be nice if we could use one tool that handles both instead of several different hand-rolled approaches, e.g.,

```js
yargs.option('b', {
  alias: 'banana',
  default: process.env.BANANA
})

I think my favorite option out of the ones outlined above is the prefix based approach, I could see using an API like this:

```js
yargs.option(h, {
  alias: 'host',
  type: 'string'
})
.env('REGISTRY_FRONTDOOR`) // where .env is passed a prefix for environment variables.
```

Running the app with the environment variable `REGISTRY_FRONTDOOR_HOST=99.9`, would then populate the `string`, `argv.host` as would `REGISTRY_FRONTDOOR_H=99.9`.

 `REGISTRY_FRONTDOOR_FOO=9.3` would be parsed as a float since we have no option configured for it.

I'd love to get a few other people's opinions, there are several ways we can go :)

CC: @disjukr, @nylen

**Comment by disjukr** [comment]
@bcoe `.env` variable prefix api would be useful. i have no other opinion

**Comment by bcoe** [comment]
Addressed in https://github.com/bcoe/yargs/pull/308
