### ISSUE TITLE
Arguments that look like floats are interpreted as floats

### ISSUE THREAD

**Issue by achingbrain** [bcoe/yargs#306]
...leading to data loss.

This is similar to #166 but it affects non-hyphenated arguments too.  E.g:

```javascript
var yargs = require('yargs');

var argv = yargs
    .argv;

console.log(argv._);
```

```shell
$ node test.js 1.0
[ 1 ]
```

Is there any way to get yargs to interpret `1.0` as `"1.0"` and so not round it to `1`?

**Comment by nexdrew** [comment]
@achingbrain You should be able to accomplish this via:

```js
var argv = require('yargs')
  .option('_', {
    type: 'string'
  })
  .argv
console.log(argv._)
```

```
$ node test.js 1.0
[ '1.0' ]
```

**Comment by achingbrain** [comment]
That works great, thanks.
