### ISSUE TITLE
Remove dynamic requirement in parser.js

### ISSUE THREAD

**Issue by scriptjs** [bcoe/yargs#312]
Dynamic requirements are poor practice that prevent bundlers from being able to package the library. The following function needs to be rewritten in parser.js

```
function setConfig (argv) {
    var configLookup = {}

    // expand defaults/aliases, in-case any happen to reference
    // the config.json file.
    applyDefaultsAndAliases(configLookup, aliases, defaults)

    Object.keys(flags.configs).forEach(function (configKey) {
      var configPath = argv[configKey] || configLookup[configKey]
      if (configPath) {
        try {
          var config = require(path.resolve(process.cwd(), configPath))

          Object.keys(config).forEach(function (key) {
            // setting arguments via CLI takes precedence over
            // values within the config file.
            if (argv[key] === undefined || (flags.defaulted[key])) {
              delete argv[key]
              setArg(key, config[key])
            }
          })
        } catch (ex) {
          if (argv[configKey]) error = Error(__('Invalid JSON config file: %s', configPath))
        }
      }
    })
  }
```

**Comment by nexdrew** [comment]
It's using `require` to read a JSON config file (not a library/module) that is specific to the end user's machine. See #304. We will eventually remove the use of `require` here to support other config file formats. Thanks.

**Comment by scriptjs** [comment]
@nexdrew I understand why there may have been the lure to use it this way. Really, this ought to be a fs.read, not a dynamic require. The problem with CommonJS in the first place is that require is a function. es6 solves this by making everything declarative and static with its import statements. The use of require like is simply just not what you want to do. Is game off in almost all circumstances for any bundler.

**Comment by bcoe** [comment]
@scriptjs if I understand this edge-case, it would be if someone bundles yargs using something like `CommonJS`, and then in the context of a browser loads a config file?

**Comment by scriptjs** [comment]
@bcoe. Its actually not an edge case. Most folks today are already writing in es6 or in the process of transitioning. If anyone attempts to bundle yargs for node, they will encounter this issue. It will not bundle without forking the code and eliminating the issue. On that basis, not sure why this issue was closed.

A short term solution is use an fs.read instead of requiring json and make your longer term changes to config that have been discussed recognizing CommonJS is on its way out. If I were you, I would be writing this module in a src folder in es6 and transpiling to a lib or dist in your project. Then pointing to the  transpiled main in your package.json. You can also create a main:jsnext in the package.json to point to the es6 entry directly so live code can be included in the es6 bundle and properly analysed for live code. Your module with then have some value for folks writing es6 and for CommonJS with entry points for either.

**Comment by bcoe** [comment]
@scriptjs when I take on the API improvements I have in mind for config parsing, I'll tackle this.

**Comment by scriptjs** [comment]
@bcoe thank you.

**Comment by bcoe** [comment]
@scriptjs one argument for using `require` rather than `JSON.parse` was that individuals would be able to require `.js` configuration -- behavior that I'm sure some installations in the wild rely on.

Any thoughts about how we could move away from require, without this being a breaking change?

**Comment by scriptjs** [comment]
I was originally looking to use yargs but decided against it for a variety of reasons. I wrote an option parser and tests in es6 last week.  Probably should not have bothered you. In the end, I could not see any way of really getting to where I needed to go without reconstruction. I'll close the issue.

**Comment by rgranger** [comment]
Hi, this issue is still up to date. I want to bundle my NodeJS server using webpack. Ofc there is this solution http://jlongster.com/Backend-Apps-with-Webpack--Part-I which does not satisfy me.

My point : I want to be able to bundle my server in a single, self-sufficient file. I don't want to have to carry around the node_modules folder with my bundled server.

Here is what I have to do to prevent Webpack from compiling defective modules : 

    const webpackConfigServer = {
      name: 'server',
      target: 'node',
      context: paths.base(),
      node: {
        __dirname: false,    // real dirname relative to the context option
        __filename: false    // real filename relative to the context option
      },
      devtool: config.compiler_devtool,
      resolve: {
        root: paths.src(),
        extensions: ['', '.js']
      },
      module: {},
      externals: {  // What I want to avoid to do
          'yargs': 'commonjs yargs',
          'socket.io': 'commonjs socket.io',
          'webpack': 'commonjs webpack',
          'html-webpack-plugin': 'commonjs html-webpack-plugin',
          'any-promise': 'commonjs any-promise',
          'natives': 'commonjs natives',
          'chokidar': 'commonjs chokidar'
      }
    }

**Comment by bcoe** [comment]
@rgranger good news, it is possible to make yargs work with webpack we just need to document it better:

https://github.com/yargs/yargs/issues/781

**Comment by rgranger** [comment]
Ok thanks ! It seems a bit hackish to do require('yargs/yargs') instead of require('yargs'), but if it works... !

**Comment by rgranger** [comment]
Well, after testing it doesn't seem to work. I did this : 

    const yargs = require('yargs/yargs')
    const argv = yargs().parse(process.argv)

And I still have this Error when trying to bundle with Webpack :

![tmp](https://cloud.githubusercontent.com/assets/5648257/24289203/8cd76684-1080-11e7-8e6f-131c7b4c6096.png)

**Comment by bcoe** [comment]
@rgranger looking at that error output, it looks like the underlying issue might be that it's attempting to pack the LICENSE and CHANGELOG.md files which aren't JavaScript;

@tcoulter, @erossignon perhaps you could provide an example of the approach that you are using?

**Comment by ezze** [comment]
@bcoe, I think that packing `LICENSE` and `CHANGELOG.md` is another in @rgranger's Webpack output. I still have [similar warnings](https://github.com/yargs/yargs/issues/781#issuecomment-345452630) trying to bundle `yargs` with Webpack 3.
