### ISSUE TITLE
Escaped Strings

### ISSUE THREAD

**Issue by alex-phillips** [bcoe/yargs#315]
This might not be a "yargs" specific issue, but this wasn't an issue before I switched from the "commander" package, but when I pass arguments in the command line with escaped spaces in a string (i.e., `/Users/example/Documents/My\ Music`), it ends up parsing it as 2 individual arguments: `/Users/example/Documents/My` and `Music`. Is there anyway around this other than putting the string in quotes?

**Comment by alex-phillips** [comment]
This may not be an issue after all. It might the the debugger displaying incorrect information (`console.log` outputs something different). Will investigate further.

**Comment by bcoe** [comment]
@alex-phillips the operating  system itself is going to be what's interpreting the `\` escape character, and passing it into yargs. I put together this minimal example:

```js
#!/usr/bin/env node

var opts = require('./')
    .argv;

console.log(opts);
```

on my OSX machine:

```sh
Benjamins-MacBook-Pro:yargs benjamincoe$ node test.js hello\ world
{ _: [ 'hello world' ], '$0': 'test.js' }
```

I'm not quite sure what might be causing you issues.

**Comment by alex-phillips** [comment]
Yup, you're right. The console logging shows the correct escaped string, it's the debugger that is the issue. Thanks!
