### ISSUE TITLE
Announcement: climaker

### ISSUE THREAD

**Issue by stelcheck** [bcoe/yargs#317]
Hi,

Just thought I would let you guys know that I have created a tool for creating CLI tools which is heavily leveraging yargs:

![climaker](https://cloud.githubusercontent.com/assets/592432/11805653/ec532fb0-a350-11e5-8cc9-69f8fe1c6197.gif)

It both provides a CLI to help with the creation for a skeleton for your CLI tool and acts as the library that will plug your binaries to commands - and defines what should be the format of the commands themselves.

Still quite raw, but hope you enjoy :)

https://www.npmjs.com/package/climaker
https://github.com/Wizcorp/climaker

**Comment by nexdrew** [comment]
Hey @stelcheck, sorry for the delayed response, thanks for sharing! I haven't had time to play with it yet, but your tool looks pretty slick.

This would be a good candidate for a "Related Packages" section in the README (which doesn't exist yet). I know of at least one other library that is meant to work with yargs. :smile: Know any others we could add? Maybe it's time we finally add this to our docs?

**Comment by bcoe** [comment]
@nexdrew I was going to chime in with the same comment -- I love the idea of this section.

... it would actually be pretty cool to have a yargs website with a section about related projects, and perhaps a section about large projects using yargs -- on that note, wouldn't a logo be nice?

**Comment by bcoe** [comment]
@stelcheck I'm going to close this, but let's create an issue to discuss what a section in the documentation (better still a website) might look like for showcasing related modules.
