### ISSUE TITLE
Documentation, website and related tools section

### ISSUE THREAD

**Issue by stelcheck** [bcoe/yargs#318]
Ref: https://github.com/bcoe/yargs/issues/317

Suggest:

1. http://readthedocs.org for documentation (where a related tool section could be). 
2. 1-pager website, with a "Who's using yargs" section
3. Readme with development howto, list of contributors and other notes.

cc @bcoe @nexdrew

**Comment by maxrimue** [comment]
For the website, a GitHub project page would probably be the best choice here, it can then be made in either Markdown or HTML/CSS (which I would prefer), but what about the domain? GitHub would provide something like `bcoe.github.io/yargs/` if I'm not mistaken, we could also buy a domain like `yargs.io` (currently not used).

Also, what about the logo? Is anyone here having experience in designing logos? If not, I could at least try myself as I have a good vector graphics programme which I am familiar with, I can create an `.svg` based on colours and style you would like to have.

**Comment by bcoe** [comment]
I wonder if @substack has any thoughts about what might make a good logo -- his artistic style pervades optimist and yargs.

**Comment by nexdrew** [comment]
About the site, we currently have a `gh-pages` branch that is available at http://yargs.js.org/ (thanks to the good folks at [JS.ORG](https://github.com/js-org)). Right now the site only consists of a client-rendered version of the README (via [Flatdoc](https://github.com/rstacruz/flatdoc)), but we could add stuff to it if you want.

**Comment by bcoe** [comment]
@nexdrew perhaps it's time that we create a yargs org, and have a separate website codebase?

**Comment by nexdrew** [comment]
@bcoe Ok by me, but another codebase is more stuff to maintain. I can see it being useful if we ever want to split up yargs into multiple libs e.g. plugins. But the further a website or documentation is from code, the harder it will be to maintain. Just my 2¢. I'm good with it either way.

**Comment by bcoe** [comment]
@nexdrew I'm working on a related issue right now, with some clarification -- I think an org is a good idea:

1. it's confusing that the `gh-pages` branch of yargs has a completely different purpose than the `master` branch -- seems better that we'd have a website repo.
2. there already are several modules that make up yargs, that we could move into the org: `cliui`, `y18n`, `yarsay` -- eventually I'll move the `yargs` project itself into the org ... but it feels like pushing my baby bird out of the nest.

**Comment by bcoe** [comment]
@stelcheck closing in favor of: https://github.com/bcoe/yargs/issues/324

**Comment by nexdrew** [comment]
@bcoe Great points :+1:
