### ISSUE TITLE
Defining an option key with "no-" in front of it

### ISSUE THREAD

**Issue by MikeyBurkman** [bcoe/yargs#322]
I'm working on a wrapper for some common command line things we do in a .NET project. One of things I'm trying to mirror is the .NET command `dnu restore --no-cache`. (The Node script will run the command automatically in a bunch of places.) I'd like the Node script's arguments to mirror dnu's, but I can't specify an option for --no-cache, as it's always seen as a negated version of --cache. 

Where this gets rather annoying is that if my yargs is configured to be strict(), then it always fails because I haven't defined a "cache" option. I can define a "cache" option and default it to true to get the same behavior, but the --help for it ends up being confusing if you're expecting --no-cache. Maybe if an option is defined to start with "no-" then negation should be ignored? Or maybe add a flag when defining an option to disable negation?

**Comment by bcoe** [comment]
Hey @MikeyBurkman our next major release of yargs allows you to turn on and off various parsing features:

You can add the following stanza to your package.json:

{
  "yargs": {
     "boolean-negation": false
  }
}

See https://github.com/yargs/yargs-parser#configuration for details.

I would love for you to try this feature out, and give some feedback:

```sh
npm i yargs@alpha --save
```
