### ISSUE TITLE
Place install instructions at the start of the Read Me file please

### ISSUE THREAD

**Issue by Vikasg7** [bcoe/yargs#323]
The Installation section is at the end of the Git Intro Page of yargs. Whenever, I search for any library on git. I always see the installation instructions at the start of Intro of any Library. In yargs case, I had to guess the install command. Later on when I scroll down for some other reason, I found the install instructions. So could you please place the install instructions at the start of the intro page. ?? That would be good for other peoples to find it.

**Comment by maxrimue** [comment]
Hey, there's currently a discussion ongoing about changes for yargs v4 (#310), one suggestion there is to change the readme in some parts, if you have some additional feedback for the readme, you can let us know there, I'll add this issue to the list of proposed changes, thanks!

**Comment by Vikasg7** [comment]
Hello,
No sir, this is the only one, I noticed.
You are doing a great jobs.
This tool is best amongst all others.

Regards,
Vikas Gautam

**Comment by bcoe** [comment]
@nexdrew how do you feel about moving the installation instructions above examples -- @substack has given the advice in the past "show some working code first" ... _but_ there are _so_ many examples, it does push the installation instructions pretty far down.

**Comment by nexdrew** [comment]
@bcoe Hmm, not sure. We talked about some of this a long time ago, and I think it'd be nice to define and comply with some standard README layout (as discussed [here](https://github.com/zcei/standard-readme/issues/1)), but don't think anyone will agree on that anytime soon. There *does* seem to be a trend of putting install before examples, so I'm in favor of moving it, but I've been hesitant to do any major overhauls of the docs. I want to respect all the work that was done before me and keep some of that substack charm. :)

**Comment by bcoe** [comment]
@Vikasg7 rather than moving the install instructions up, we're working on a slick new yargs website to help onboard people:

http://yargs.js.org/

This will be linked to predominantly at the top of the documentation.
