### ISSUE TITLE
 the future of yargs

### ISSUE THREAD

**Issue by bcoe** [bcoe/yargs#324]
2015 has been a great year for yargs:

* we're now one of the [top 50](https://www.npmjs.com/browse/depended) most depended upon modules on npm.
* we're being used on by some amazing open-source-projects like [Atom](https://github.com/atom/atom/blob/master/package.json).
* we've squashed many bugs, and released many awesome features.

Great work everyone \o/ (with special shout outs to @nexdrew, @sindresorhus, and @maxrimue).

I've been thinking a little bit about what the future holds for yargs ...

## Creating a Yargs Organization

It would be great to create a yargs organization to group together the modules that we develop:

* [y18n](https://www.npmjs.com/package/y18n): our internationalization library.
* [cliui](https://www.npmjs.com/package/cliui): our UI layout library.
* _the website_: currently the website sits on a `gh-pages` branch, pulling this into its own repo would help us better iterate on a slick website for yargs.

## A Website For Yargs

We have a bare-bones website for yargs, it would be nice to have something a bit slicker:

* there are some amazing OSS projects using yargs, .e.g., Atom, I would like to showcase this on a landing page.
* it would be nice to have a page where folks can advertise their projects, and tools related to yargs (https://github.com/bcoe/yargs/issues/318).
* we should have a quick-start guide, along with more thorough documentation.

## A Logo For Yargs

The yargs org, and the new yargs website need a logo that we can rally behind. I would love to see what the community comes up with.

-----

I'm looking forward to 2016, thanks to everyone for your hard work this year.

**Comment by nexdrew** [comment]
Can't believe yargs is growing up! This is exciting stuff.

@bcoe yargs would obviously not be what it is today without you - thanks so much for your awesome work and your contributions to the FOSS Node community at large! It's a privilege working with you.

**Comment by lrlna** [comment]
Hi hi! Carrying over the conversation form twitter to here: would love to help with website in the new year :star2: 

I completely agree with having it on another repo. With a project of this size and popularity will be useful to have two and not have `master` and `gh-pages` being entirely different code bases :+1:

**Comment by bcoe** [comment]
@lrlna awesome \o/ 

Send an email to `ben@npmjs.com`, and I'll get you added to the yargs slack -- actually I @maxrimue could you do the same? (it's pretty much just @nexdrew and I in the slack right now).

**Comment by lrlna** [comment]
@bcoe :cool:, emailing right now!

**Comment by bcoe** [comment]
<img width="940" alt="screen shot 2015-12-31 at 2 37 06 pm" src="https://cloud.githubusercontent.com/assets/194609/12068853/1bd50b00-afcc-11e5-8d81-1bfbae90ad2a.png">

yargs in 2015 ^

**Comment by maxrimue** [comment]
Sure, would be cool! I have to get in touch with Slack first as I've never
used it, I'm just celebrating New Year's Eve in Germany here right now so
I'll have to do it tomorrow

**Comment by chrisdickinson** [comment]
I'll turn this into more of a logo in a bit:

<img width="475" alt="screen shot 2015-12-31 at 5 34 39 pm" src="https://cloud.githubusercontent.com/assets/37303/12069651/d0ce8b7c-aff3-11e5-9c1a-2b003b734acc.png">

I'll also put together some other options!

**Comment by nexdrew** [comment]
@chrisdickinson Whoa, nice!

Ok that's just a _little_ better than mine:
<img width="570" alt="screen shot 2015-12-31 at 10 41 39 pm" src="https://cloud.githubusercontent.com/assets/1929625/12069676/d1e0f51a-b00f-11e5-8a56-20886c768b19.png">

**Comment by bcoe** [comment]
@chrisdickinson I'm really digging this design :)

@nexdrew I think as soon as yargs makes a foray into South Park, this design is perfect.

In all seriousness, this is getting me very excited to start working on the yargs website.

**Comment by nexdrew** [comment]
I knew you'd like it. :P

FYI I set my "y" as the org logo in GitHub, but I just meant it to be temporary. Feel free to swap it out with one of Chris's awesome graphics.

Happy 2016 Everyone! :v:

**Comment by jameswomack** [comment]
A minimal interpretation of the pirate, along with CLI-inspired type. Interlaced transparent PNGs. 

![yargs-02](https://cloud.githubusercontent.com/assets/77849/12076120/a8e666aa-b153-11e5-8e2c-6303a83dbe81.png)
![yargs-01](https://cloud.githubusercontent.com/assets/77849/12076121/a8eafef4-b153-11e5-9299-1bf234a1ba1e.png)

**Comment by bcoe** [comment]
Some thoughts so far:

I really like @chrisdickinson's rendering as an overall look and feel that we could shoot for with the website -- big fan of color scheme, and the boat as imagery we can use throughout the site.

It seems like @jameswomack and @nexdrew have some similar thoughts about what we should gun for with regards to a minimal logo: I'm torn between @nexdrew's simple rendering of a **y**, @jameswomack's **$yargs**, and @chrisdickinson substack-inspired hand-drawn **yargs**.

Curious if we can work together and come to a look and feel we're all excited a about.

CC: @Irina.

**Comment by bcoe** [comment]
one thing that comes to mind, perhaps elements of @jameswomack icon work, incorporating the color scheme from @chrisdickinson's rendering -- I like the eye-patch a lot, rather than using @nexdrew's **Y** perhaps we use just the eye-patch, with colors from @chrisdickinson's rendering.

**Comment by chrisdickinson** [comment]
I'll spend some time on this tonight. I'd like to turn the pirate ship into a hexa-logo, with small block white border text surrounding that reads "maybe if we ask nicely they'll just give us their riffiewobbles;" and I'd like to rework the yargs text itself (it's a little weak right now.) Character-wise, I'm thinking of moving away from "human pirate" since that gets into weird/unnecessary specificity. Will post some options tonight.

**Comment by jameswomack** [comment]
@bcoe Before I saw your last post I'd gotten to work on incorporating Chris' colors

@chrisdickinson I began to feel the same (re: showing a human-pirate), so when pulling in some of your colors, I eliminated the face and teeth

New images: bg pattern, patch-only and patch & hat logos

![yargs_02-04](https://cloud.githubusercontent.com/assets/77849/12076319/9b671666-b15b-11e5-8d6d-41752e4ec5e8.png)
![yargs_02-03](https://cloud.githubusercontent.com/assets/77849/12076320/9b6b1a7c-b15b-11e5-96ce-1b3a761742c1.png)
![yargs_02-02](https://cloud.githubusercontent.com/assets/77849/12076321/9b6eff8e-b15b-11e5-9748-87ac8678a489.png)

**Comment by bcoe** [comment]
@chrisdickinson @jameswomack @nexdrew really excited to see what this converges on :+1:

**Comment by nexdrew** [comment]
My stuff is silly and should not be taken seriously.

I agree with @bcoe that we should use @chrisdickinson's work for site-wide colors and L&F.

For a logo, I like @jameswomack's idea of incorporating a *$* symbol, representing a shell prompt and pirate booty. How about something like that on a pirate flag for a logo? Then we could easily tie that in with Chris's boat, flying the colors at mast.

I dunno, just thinking out loud here.

**Comment by lrlna** [comment]
The colour scheme on that entire last set is brilliant @jameswomack. I also really like the minimalism of. it. :+1: for the patch :+1: for the hat. The teeth on the first iteration was too much detail, I thought. 

Which made me think a little animation of that pirate on the website on load would be p cool :heart_eyes: .

**Comment by jameswomack** [comment]
I also like the UNIX-y hacker cred feel of having the $, and it makes sense
with the pirate/merchant ship theme. And yes, the teeth seemed to distract
from, rather than add to, the core idea.

Any ideas on what the animation could be? I'd be happy to implement the
animation.

Also, happy to share the SVG assets representing the patch etc.

On Saturday, January 2, 2016, Irina Shestak <notifications@github.com>
wrote:

> The colour scheme on that entire last set is brilliant @jameswomack
> <https://github.com/jameswomack>. I also really like the minimalism of.
> it. [image: :+1:] for the patch [image: :+1:] for the hat. The teeth on
> the first iteration was too much detail, I thought.
>
> Which made me think a little animation of that pirate on the website on
> load would be p cool [image: :heart_eyes:] .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bcoe/yargs/issues/324#issuecomment-168450032>.
>


-- 
James J. Womack
Senior Software Engineer/Architect
Netflix

**Comment by lrlna** [comment]
For animation I am so far thinking about:

- ship moving through the waves in the sea
OR
- pirate swaying from side to side. 

It would have to be pretty minimal, I wouldn't want it to be too distracting. I've never done animation with css, so yes that would be awesome if you wanted to implement it. 

SVG assets would be awesome as well. I am just currently plugging in what I saw above just to get a feel for what we want to do in actuality :dancers:

**Comment by bcoe** [comment]
@lrlna this sounds wonderful; I love the ship idea, it would let us integrate @chrisdickinson's lovely illustration with some of the slick logos @jameswomack has furnished us with.

Perhaps we could use CSS3 animations, and fallback to a static image -- or, if we're feeling adventurous perhaps some shims exist that we can fallback to?

**Comment by jameswomack** [comment]
@lrlna 
[SVGs.zip](https://github.com/bcoe/yargs/files/79191/SVGs.zip)

**Comment by jameswomack** [comment]
![yargs_patch_n_hat](https://cloud.githubusercontent.com/assets/77849/12130746/e9b9adc0-b3c1-11e5-878b-66c2f90f519d.gif)

**Comment by bcoe** [comment]
we're making good progress in a slack organization now \o/
