### ISSUE TITLE
Allow args string in .parse()

### ISSUE THREAD

**Issue by kellyselden** [bcoe/yargs#327]
Use case is your program wraps other programs:

```sh
my-app --an-option test --a-wrapped-programs-options="--test x --another=s"
```

The closest config I got was something like:

```js
var yargs = require('yargs');

var argv = yargs.argv;

var aWrappedProgramsOptions = argv['a-wrapped-programs-options'];

aWrappedProgramsOptions = yargs.reset()
    .parse(aWrappedProgramsOptions);
```

But parse only takes an array. I thought I could do something like `aWrappedProgramsOptions.split(' ')`, but that doesn't account for `=` delimiters. If I go further, I start implementing some of the logic in yargs already.

Would it make sense to allow strings in `.parse()`?

**Comment by bcoe** [comment]
@kellyselden you should be able to do something like this:

```js
#!/usr/bin/env node

var opts = require('yargs')('--test x --another=s'.split(' '))
    .argv

console.log(opts)
```
yargs let's you pass an array representing `argv` as an argument to `yargs`.

Does this do the trick for you?

**Comment by kellyselden** [comment]
That works. I didn't realize yargs would handle `=` for you, and you wouldn't have to split on it. Is this use case worth a README update? I can update it if you want.

**Comment by bcoe** [comment]
@kellyselden happy to consider a README update, if you can find an elegant way to outline this tidbit of information :+1:

**Comment by bcoe** [comment]
@kellyselden give: https://github.com/bcoe/yargs/pull/331 a shot and let me know what you think.

**Comment by kellyselden** [comment]
LGTM

**Comment by bcoe** [comment]
@kellyselden this feature is now released on the `next` tag of yargs. Give this a shot:

`npm i yargs@next`

Let me know what you think :+1:

**Comment by kellyselden** [comment]
@bcoe Works great. Was able to remove this line https://github.com/kellyselden/eslint-mocha/pull/17/files#diff-dec258563532f674fb4d25d7d9952de6L22

Thank you.
