### ISSUE TITLE
Named positional arguments

### ISSUE THREAD

**Issue by stevage** [bcoe/yargs#333]
I looked through the docs twice and I couldn't find any way to give names to positional arguments. That is, for a command like:

`cp <source> <dest>`

I was expecting to be able to do something like:

```
var yargs = require('yargs')
    .options({
    'source' : {
        'description' : 'File to copy',
        'positional': true
    },
    'dest' : {
        'description' : 'Where to copy to',
        'positional': true
    });

console.log(yargs.argv.source);
...
```

Currently it seems you have to do this:

```
var yargs = require('yargs')
    .usage('$0 source dest');

var source = yargs.argv._[0];
var dest = yargs.argv._[1];
```

Positional arguments are pretty central to Python's [`argparse`](https://docs.python.org/3.3/library/argparse.html) library, for instance.

**Comment by nexdrew** [comment]
@stevage Thanks for the suggestion!

`.options()` are for flag-based arguments, e.g. `--source file.txt`, that are typically optional but could also be required. Support for these is fairly extensive.

For "flagless" arguments like you describe, yargs does not currently support mapping those to names/aliases. But we're planning on overhauling the commands API in 4.x, so we can add this to our radar/roadmap.

In the meantime, you could do something like this:

```
var source = 0, dest = 1
var argv = require('yargs')
  .usage('$0 <source> <dest>')
  .help('h').alias('h', 'help')
  .argv
source = argv._[source]
dest = argv._[dest]
```

Which is not great, but at least allows you to present the help text as desired and use a pseudo-alias for unnamed args.

**Comment by nexdrew** [comment]
See #121

**Comment by stevage** [comment]
Ah yep, very similar to what I did:

```
var yargs = require('yargs')
    .usage('$0 [options] [path/to/wwwroot]')
    .options({
    // flagged options here
    }
});

var argv = yargs.argv;
argv.wwwroot = argv._[0];
```

**Comment by bendavis78** [comment]
What about something like this:

    var argv = require('yargs')
      .usage('$0 [options] <source> <dest>')
      .demand(2).annotate(1, 'source').annotate(2, 'dest')

**Comment by stevage** [comment]
In my actual case that wouldn't quite work, because the two positional arguments are optional (although the second requires the first).

**Comment by bcoe** [comment]
@stevage @bendavis78 see https://github.com/bcoe/yargs/pull/368, named positional arguments are close to landing.

**Comment by douniwan5788** [comment]
> @stevage @bendavis78 see #368, named positional arguments are close to landing.

I don't understand, how is the `commands` related to `named positional arguments`?
