### ISSUE TITLE
`group` property displays option twice

### ISSUE THREAD

**Issue by alex-phillips** [bcoe/yargs#336]
When I pass in multiple options using `.options({})` and the options in the object have the `group` property, it honors the group but each option is listed twice.

**Comment by nexdrew** [comment]
Would you mind posting some sample code?

**Comment by alex-phillips** [comment]
So it appears the issue is not that the `group` property is set, and maybe its because I'm mis-using the package, but if you take a look at my example, I'm essentially trying to have 'global' options in all commands and then command-specific options.

If you run my code with no command, it produces the global options individually. However, if you pass in a command  with `-h` to get the help text, the global options are all listed twice.

I was under the assumption that when you call `yargs.command` and use the `argv` passed in, everything was 'reset' in a sense so that I didn't have to worry about double adding options. Is this not the case?

Let me know if you need more context in my sample code.

Also, is there a way to change the order of groups? In the commands for example, I'd like `Flags` to be listed before `Global Flags`. Changing the order of how they're adding doesn't seem to fix that.

https://gist.github.com/alex-phillips/15591894811cbd1d55b1

**Comment by nexdrew** [comment]
@alex-phillips Thanks, that helps a lot!

I am AFK at the moment but I think the `groups` are not being cleared in the `reset()` method. Not sure if this was deliberate, will need to check and add tests.

**Comment by alex-phillips** [comment]
Thanks for the info! Just keep me posted with what you find if you don't mind. If a fix is needed, I'd be more than happy to check it out and open a PR.

**Comment by bcoe** [comment]
@nexdrew this definitely seems like a bug we should put tests around and fix :+1: I don't remember doing this deliberately.

**Comment by alex-phillips** [comment]
@Bcoe not an issue but somewhat related: is there a way to control the order of the groups as I mentioned above?

**Comment by bcoe** [comment]
@alex-phillips if I recall, the goal was to keep the order of definition, if we don't have tests around that behavior we should add some -- it might be that the `reset` bug you're running into is causing issues with ordering.

**Comment by nexdrew** [comment]
Yes, resetting the `groups` will fix the order problem too. In your example, the `Global Flags:` group is actually added first, and then the `Flags:` group per command is added when the command handler is run, followed immediately by the `Global Flags:` group again. If the `groups` were reset for the command handler, then it would respect your intended order.

I'm working on fixing this and came across a weird scenario. What should yargs do here:

```js
yargs.group(['batman', 'batman'], 'Heroes:')
```

I assume it should only use one of the duplicated options in help text. Right now it doesn't, but is this a "garbage in, garbage out" predicament, or should yargs check for duplicates?

**Comment by bcoe** [comment]
@nexdrew when it doesn't add too much logic, I've tended to try to make yargs as bullet proof as possible -- probably worth protecting folks from this accident.

**Comment by nexdrew** [comment]
@alex-phillips Until we get a fix out for this, you can probably work around it by adding this to the beginning of your command handler function, which manually resets the groups:

```js
var groups = yargs.getGroups()
Object.keys(groups).forEach(group => delete groups[group])
```

**Comment by alex-phillips** [comment]
@nexdrew works like a charm! Thanks for being so proactive on this, guys. This is awesome. 

Also goes without saying, this is the best CLI parser / framework I've ever worked with (including in my PHP and Ruby projects).

**Comment by nexdrew** [comment]
@alex-phillips Wow, that is a great compliment that I'm sure none of us take lightly. Thanks!
