### ISSUE TITLE
camel casing problems with .default(..

### ISSUE THREAD

**Issue by davibe** [bcoe/yargs#341]
If i pass an option like `--this-option` yargs auto creates the camel cased version so the argv object includes `this-option` and `thisOption`. 

On the other hand if i specify .default('this-option', 'value') and i don't pass any `--this-option` arg then the `argv` does not contain camelCased version with default value. Only `this-option` is present

**Comment by bcoe** [comment]
@davibe try the upcoming release of yargs, and let me know if this solves the problem for you:

`npm i yargs@next`

:+1:
