### ISSUE TITLE
parse boolean argument wrong

### ISSUE THREAD

**Issue by kerryChen95** [bcoe/yargs#345]
build.js:
```
let argv = require('yargs')
  .options({
    noWatch: {
      demand: false,
      default: false,
      type: 'boolean',
    },
  })
  .argv

console.log('argv.noWatch: ' + argv.noWatch)
console.log('argv["no-watch"]: ' + argv['no-watch'])
console.log('argv.watch: ' + argv.watch)
```

---

```
$ node build --no-watch
argv.noWatch: false
argv["no-watch"]: undefined
argv.watch: false
```
I think `argv.noWatch` should be true, `argv["no-watch"]` should be true, isn't it?

---
```
$ node build --noWatch
argv.noWatch: true
argv["no-watch"]: undefined
argv.watch: undefined
```
I think `argv["no-watch"]` should be true, `argv.watch` should be false, or `argv.watch` is undefined for both commands `node build --no-watch` and `node build --noWatch` 

---
Version info:
yargs@3.31.0
node@v4.2.2

**Comment by maxrimue** [comment]
I think this issue is similar to #322.
What happens here is that `--no-watch` gets interpreted as `set "watch" to false`, yargs usually does this if you write options with two dashes in front, add a `no`, and then another name behind like you did here. This is why you have to use `--noWatch` as in the second example, and it's also why `argv.noWatch` equals to `false` in the first example because `--no-watch` __only__ sets `watch` to false.

To the other issue that `argv["no-watch"]` doesn't work is that this it's simply not the name of the option, it's `noWatch`, and yargs does not automagically create an alias for this. So to fix this, you only can access the option with either `argv['noWatch']` or `argv.noWatch`, as adding the alias `no-watch` would require you to type `--no-watch`, which would again make yargs parse it as `set "watch" to false`.

**Comment by bcoe** [comment]
@kerryChen95 can you get away with using:

```js
let argv = require('yargs')
  .options({
    watch: {
      default: true,
      type: 'boolean',
    },
  })
  .argv
```

This would allow you to run:

```
./my-bin --no-watch
```

If so shall we close this issue?

**Comment by kerryChen95** [comment]
@bcoe I have set options key to `watch` as you do and it does work. So can I say we should not configure an argument that is prefixed with `no`, regardless of camelCase or `-` separator? Because prefix `no` is just used to set a boolean argument to false.

@maxrimue 
Can yargs support both camelCase and `-` separator. If so, developer can configure any one of these two styles, yargs can accept both two styles in command line, and `argv` object provides both two styles properties.

And can yargs does as below?
If prefix `no` does not appear in command line, for example `--watch`, yargs set `argv.watch = true` and let `argv.noWatch` & `argv['no-watch']` just `undefined`.
Only if prefix `no` appear in command line, for example `--no-watch` or `--noWatch`, yargs set `argv.watch = false` and `argv.noWatch = argv['no-watch'] = true`.

**Comment by maxrimue** [comment]
@kerryChen95 yargs does support option names like `some-option`, here, we only have the problem that your option's name starts with `no`, which makes yargs parse as I describe above. Usually, you can also apply aliases to options, say you have an option called `some-option` and also want to support the name `someOption`, you could write code like this:
```javascript
let argv = require('yargs')
  .options({
    someOption: {
      alias: 'some-option',
      type: 'boolean' //Could be any type
    },
  })
  .argv
```
Now, both of these commands would make both `argv['some-option']` and `argv['someOption`] equal to `true`:
```shell
node build --some-option
```
and
```shell
node build --someOption
```   
   
The only problem you would have is that the name `no-watch` starts with `no`, so you would have to type `--no-watch`, which means yargs would parse it as `watch = false` again. I would recommend you to use @bcoe's code:
```javascript
let argv = require('yargs')
  .options({
    watch: {
      default: true,
      type: 'boolean'
    },
  })
  .argv
``` 
This way, if you type:
```shell
node build --no-watch
```
`argv['watch']` will equal `false`, and if you don't add `--no-watch` to the command, `argv['watch']` will equal `true`. Does this solve your issue?

**Comment by kerryChen95** [comment]
@maxrimue thx, I got it

**Comment by bcoe** [comment]
@kerryChen95 closing in favor of this ticket: https://github.com/bcoe/yargs/issues/352

**Comment by JasinYip** [comment]
This is an unusal design. As we can see most usages are determined as `true` while the boolean flag had given, like Node.js' flags, npm `--save-dev`, etc.
