### ISSUE TITLE
[Question] Is any way to disable dot notation? 

### ISSUE THREAD

**Issue by btd** [bcoe/yargs#349]
I have legacy system, that pass command line arguments with dots, and it will be easier for me at the end to have them as properties, not nested objects.
Is any way to disable dot notation behavior or have both version in result?

**Comment by bcoe** [comment]
duplicate of: https://github.com/bcoe/yargs/issues/351

One thought I have is perhaps `yargs@4` could have a configuration setting for this.

**Comment by btd** [comment]
That will be nice. I will fork it for a while.
