### ISSUE TITLE
make yargs configurable

### ISSUE THREAD

**Issue by bcoe** [bcoe/yargs#352]
It would be nice to be able to enable and disable some of yargs' more controversial parsing functions, e.g., `--no`, dot-notation.

There are several tickets that request the ability to do so:

https://github.com/bcoe/yargs/issues/345
https://github.com/bcoe/yargs/issues/349

I propose that we make the yargs parser configurable:

* I appreciate how AVA simply loads its configuration from `package.json`, I'd prefer that we start with an approach like this rather than pulling in a library like `rc`.
* the default configuration would be all current parsing options turned on, an individual could then disable features such as `dot-notation` by adding:

```json
{
  "yargs": {
    "dot-notation": false
  }
}
```

**Comment by btd** [comment]
In your case it will make configuration global (the same way you can use environment variables). 
I am :+1: but probably better to make this configurable also per option also.

**Comment by maxrimue** [comment]
@bcoe Should we accept configuration only via `package.json` or just add it to the possibilities of passing configuration? Also, how should yargs know whether to parse the `package.json`'s content or not if it's not the only option, maybe via `.config()`?

**Comment by lrlna** [comment]
I like the idea of having it go with `.config()`; in my mind everything pertaining to my application will be inside my application, including my configurations. 

However, I do feel like that's pretty heavy for the applications users will be building. That's almost like configuring the application every time yargs does it's usual parsing magic. 

I am assuming the way we want `package.json` to work is install only certain parts of yargs (i.e. with disabled `dot-notation`, etc). Meaning the user's application doesn't worry about dealing with configuration, or does that still happen at run-time?

**Comment by bcoe** [comment]
@btd, @kerryChen95 could you give our `4.x` alpha branch a shot, and see if it does the trick for you:

`npm i yargs@alpha --save`

You can now add a stanza to your package.json to disable dot notation (and other parsing features):

```json
{
  "yargs": {
     "dot-notation": false
  }
}
```

See https://github.com/yargs/yargs-parser#configuration for details.
