### ISSUE TITLE
String argument default only if in the list of arguments

### ISSUE THREAD

**Issue by jlanza** [bcoe/yargs#361]
This is an enhancement.
I would like if possible something like having an string parameter that in case is empty it takes the default value. It is like having a boolean and string in the same.

I don't know if this is the usual way, but for instance you can have a -f flag that means to direct to file. Then you can have on your configuration a default value that is only taken if the flag -f is in the command line and is empty.

```
$ node app.js
output to console
$ node app.js -f
output to default file
$ node app.js -f outputfile
output to outputfile
```

Right now I'm using
```
  if (typeof argv.file !== "undefined" && argv.file === "") {
    argv.file = "outputfile";
  }
```

**Comment by maxrimue** [comment]
So, basically, what you would want is a `.default()` method for yargs that only applies a default value if the option is passed to the module?

**Comment by jlanza** [comment]
Yes. For boolean, it has no sense, but it might have it for strings. Maybe as another option besides default value. The problem is when you set the default value and the option is not included then there is no way to check if it has been or not requested.

**Comment by maxrimue** [comment]
@bcoe is currently attempting to make yargs more configurable (#352), there could be an `apply-defaults-if-undef` option which would default to `true`, if you set it to `false`, `.default()` will only apply defaults if the options are defined (so, passed). How does that sound?

**Comment by jlanza** [comment]
I think it sounds good ;) Thanks a lot.

**Comment by maxrimue** [comment]
@bcoe How do you feel about adding this feature like in [yargs-parser/#1](https://github.com/yargs/yargs-parser/pull/1)?

**Comment by bcoe** [comment]
I'm so so on this; my experience with most CLIs has been:

1. you have a sane default that you apply to a key.
2. If you need to set the key you're going to specify it as a key value  pair.

I think having a key behave as both a Boolean and a key/value pair could ultimately confuse people, more than it provides a useful shorthand.

@jlanza have you seen this behavior in any other CLI apps that I could use as a reference -- my gut is that it might be edge-case enough that it's worth sticking with your special logic, or moving away from this approach :)

CC: @nexdrew any thoughts?

**Comment by nexdrew** [comment]
I guess I understand the use-case but it does seem a little atypical and easy enough to work around. I could be convinced otherwise, but, personally, I don't see a lot of value in building support for this in yargs.

**Comment by bcoe** [comment]
@jlanza do you think you can stick with the workaround? Perhaps you can pull this into a helper module so that it's not too painful?

**Comment by jlanza** [comment]
Surf. There's no problema. I was just asking. But I also agree wit you that maye there are not going to be many cases. Actually I can set a Boolean for the opposite an check it first (--nofile).


Btw can you redirect me to where the helper is and I can make the pull suggested?


Thanks for the great module.





From: Benjamin E. Coe
Sent: ‎Sunday‎, ‎January‎ ‎31‎, ‎2016 ‎00‎:‎20
To: bcoe/yargs
Cc: jlanza





@jlanza do you think you can stick with the workaround? Perhaps you can pull this into a helper module so that it's not too painful?

**Comment by bcoe** [comment]
@jlanza I'll write some sample code for you tomorrow that helps you solve this problem in a repeatable way :+1:
