### ISSUE TITLE
Populate argv with named positional arguments from command string

### ISSUE THREAD

**Issue by nexdrew** [bcoe/yargs#362]
Related to #234 and #333.

I think this is something `commander` got right and we should model similar support in `yargs` (or `yargs-parser`).

Basically, map positional arguments to option names, translating arguments in angle brackets as required (e.g. `<requiredArg>`) and arguments in square brackets as optional (e.g. `[optionalArg]`).

Something similar to:

```js
var argv = require('yargs')
  .command('push <remote> [branch]', 'Push a local branch to a remote destination', function (yargs, argv) {
    console.log('remote:', argv.remote, '\nbranch:', argv.branch)
  })
  .argv
```

```
$ my-program push origin master
remote: origin
branch: master

$ my-program push origin
remote: origin
branch: undefined

$ my-program push
Commands:
  push <remote> [branch]  Push a local branch to a remote destination

Missing required argument: remote
```

It seems that supporting named positional arguments is really just shorthand DSL for minimal option configuration (besides the flagless parsing), i.e. `<requiredArg>` is equivalent to `yargs.demand('requiredArg')`.

Some implementation details to consider:

1. Does it only apply to `command()`, or does it also apply to `usage()`? We could probably support it in `command()` without a breaking change (3.x), but supporting it in `usage()` would definitely be a breaking change (4.x).
2. Do we allow optional positional arguments to be precede required positional arguments (e.g. `push [optional] <required>`) or even allow them to be interspersed (e.g. `push <required1> [optional1] [optional2] <required2>`), and is this feasible for parsing?
3. Do we allow standard `option()` configuration to apply to named positional arguments, for declaring things like `type` and `default`? And fallback to standard boolean/number/string parsing if no key-based config is given? How does this affect usage/help content?
4. Do we also support variadic arguments like `commander` (e.g. `push <remote> [branch...]`)? Perhaps this is just shorthand for explicitly configuring the option as `type: 'array'`?
5. If we support standard `option()` configuration for named positional arguments, do we also support them as flagged options as well, e.g. such that `push upstream` and `push --remote upstream` are equivalent?

**Comment by nexdrew** [comment]
This could possibly make it easier to implement #201, though we'd probably need to add a `path` option type (or maybe `file` and `directory` option types).

**Comment by bcoe** [comment]
@nexdrew addressed in https://github.com/bcoe/yargs/pull/368, in this first pass:

* we don't allow optional and required positional arguments to be interspersed. I think we could add this in `v2` without a breaking change -- and I'd like to start simple (we've had v4 of yargs on the wire for a long time and I'd like to get it out the door).
* this first pass also doesn't support `variadic` optional arguments, this would be a great addition in the future -- perhaps see how long it takes someone to request it.
* I have implemented commands in usage, but it's quite simple:

```shell
Commands:
  foo <bar> [snuh]  foo command

Options:
  --help  Show help                                                    [boolean]
```

I'm excited about this new feature, I think our discussions about commands have paid off in a much better API.
