### ISSUE TITLE
Separate command config from command execution

### ISSUE THREAD

**Issue by nexdrew** [bcoe/yargs#363]
Allow the configuration/intentions of a command (i.e. its options and usage text) to be defined upfront in a declarative way, separately from the handler that executes when the command is called.

The semantics should work for commands defined within the same module/file (perhaps an object structure or chainable config methods) or for commands defined across different submodules (conforming to expected `exports` or API).

Would be nice to support a convention-over-configuration model for submodules, if possible. Meaning something like auto-discovering command submodules in a configured directory or something.

This probably implies the need for "global" or context-specific options, i.e. options that apply to nested levels, where "global" just means the top level. For starters, this would make sense for `help()` and `version()` options but could also apply to other options shared across commands or nested contexts.

See related #121, #202, #225 (lots of comments), #288

**Comment by bcoe** [comment]
@nexdrew @iarna @maxrimue, okay I think I've got an idea for how to make commands better. How do do you feel about this syntax:

```js
#!/usr/bin/env node

require('./')
  .version()
  .command(
    'push <source> [target]',
    function (yargs) {
      yargs
        .option('name', {
          describe: 'a username'
        })
        .option('password', {
          describe: 'a password'
        })
    },
    function (argv) {
      // this will get called if, help
      // version, validation, etc, passed.
    })
  }
  .version()
  .alias('v', 'version')
  .help()
  .alias('h', 'help')
  .globals(['help', 'version'])
  .argv
```

* rather than getting `yargs` passed in as an argument to the command handling function, you provide two functions:
  * the first function builds the yargs object for the command.
  * the second function will get executed with a parsed argv: as long as `--version`, `--help`, etc hasn't forced an early exist.
* we'll introduce the `globals` feature, which allows you to specify that certain arguments should remain across the commands, e.g., I can call `foo.js push --help`.
* we'll introduce the concept of positional arguments, as @nexdrew suggested.

**Comment by lrlna** [comment]
I like it, @bcoe. It seems to fix a bunch of issues folks have been having with commands. 

We probably will have to do some education about this change though (as I guess with everything under 4.x branch); I don't want people panicking about commands, cause that's my favourite feature :tada: :dancers: 

Aside from that, I am not quite clear on the use of globals (sorry if you've talked about this previously!). Is `.command()` the only place we are planning to use this, or is this a more prominent feature? 

Will look through your #368 next :smile:

**Comment by nexdrew** [comment]
I definitely like how this simplifies the command handler function, but I'm not too sure about using the full yargs API for the command config function - could we possibly simplify that a bit more? I guess it provides for the most robust/flexible approach, but I feel like that's part of what made the 3.x command API confusing. Do we expect/allow folks to specify anything in a command config other than just options? Are you thinking of nested subcommands? Could we not get away with just accepting an object of options config (instead of a synchronous function)? Or maybe provide a subset of the yargs API?

I could perhaps see something like this:

```js
require('yargs')
  .command(
    'push <source> [target]',
    'Push something somewhere',
    {
      source: { // positional required
        type: 'string'
      },
      target: { // positional optional
        default: 'master',
        type: 'string'
      },
      name: { // flag optional
        alias: 'n',
        describe: 'a username',
        type: 'string'
      },
      password: { // flag optional
        alias: 'p',
        describe: 'a password',
        type: 'string'
      }
    },
    function (argv) {
      console.log('you called: push', argv.source, argv.target)
      if (argv.name) console.log('with name:', argv.name)
      if (argv.password) console.log('and password: [secret]')
    }
  )
  .help().alias('help', 'h')
  .version().alias('version', 'v')
  .globals(['help', 'version'])
  .wrap(null)
  .argv
```

Where maybe we categorize or indent command-specific options in help/usage output:

```
Commands:
  push <source> [target]  Push something somewhere

  Command Args:
    source  Where to push from  [string] [required]
    target  Where to push to  [string] [default: "master"]

  Command Options:
    -n, --name      a username  [string]
    -p, --password  a password  [string]

Global Options:
  -h, --help     Show help  [boolean]
  -v, --version  Show version number  [boolean]
```

**Comment by bcoe** [comment]
@nexdrew as a compromise between our two approaches, I'd like to detect whether an object is passed to the builder function, in which case I'll use an approach similar to what you've suggested. If a function is passed to the builder function, I'll assume the full-featured yargs handler.

I like the idea of grouping options into sub-headings, but I think this should potentially wait until `v2`.

**Comment by bcoe** [comment]
@nexdrew addressed in:

https://github.com/bcoe/yargs/pull/368
