### ISSUE TITLE
calling help() without arguments should not generate the usage string

### ISSUE THREAD

**Issue by bcoe** [bcoe/yargs#367]
I think that rather than `help()` returning a usage string, calling `help()` with no arguments should instead enable `help` for the default argument `--help`.

This is more consistent with the new behavior of `--version`.

If someone wants to show help, they should call `showHelp()`.

What do you think: @nexdrew, @lrlna?

**Comment by maxrimue** [comment]
Definitely a fan of this idea! :+1:

**Comment by nexdrew** [comment]
Agreed, good idea :+1:

**Comment by lrlna** [comment]
seems super reasonable :100:

**Comment by lijunle** [comment]
I love the consistence between `.help()` method with other methods. However, please provide a way to get the help message.

In my case, the app is doing some customized validation after pass, if it fails, an error message with the generic help message is shown. After this change, I cannot get the generic help message.

Any ideas on this?

**Comment by nexdrew** [comment]
@lijunle There are still a couple options, though they may be less convenient:

1. If you just want to print the help message, you can use `yargs.showHelp()` (to print to stderr) or `yargs.showHelp('log')` (to print to stdout).

2. If you want the help message as a string, you can use `yargs.getUsageInstance().help()`.

Either of these would work in, for example, a [custom fail function](http://yargs.js.org/docs/#methods-failfn).

If this isn't what you're looking for (or presents a problem with what you're trying to do), I think it's reasonable to open another issue requesting a new method that reinstates the logic of the 3.x version of `.help()` with no args, possibly named `.getHelp()` or similar. Thanks!

**Comment by lijunle** [comment]
Although `yargs.getUsageInstance().help()` is long and seems using an internal API, it is working. Thanks @nexdrew
