### ISSUE TITLE
Array of string

### ISSUE THREAD

**Issue by Alphapage** [bcoe/yargs#372]
Hello,

I need to get an array of string, but if I write .1, then I get 0.1 instead of ".1".
My code is the following:
```js
.array("a", {
        alias: "arr",
        default: null
})
```
and my command line is:
```js
node test.js -a .1 ''
```

And how to get an empty string in the array ? In my example, I get:
argv.a[0] = 0.1
argv.a[1] = ''

What am I missing?

Thanks in advance for your help.

**Comment by maxrimue** [comment]
@Alphapage The reason why this happens is that `yargs`'s parser, [`yargs-parser`](https://github.com/yargs/yargs-parser), automatically coerces strings to numbers if possible. Since `.1` is coercible to a number via `Number()`, `yargs` gives you that instead. If you don't want this to happen, you can disable this feature of the parser in the newest version of `yargs`, v3.32.0. All you need to do is add a `yargs` object to your project's `package.json` and pass in the configuration like this:
```json
{
  "name": "MyModule",
  "version": "1.0.0",
.
.
.
  "yargs": {
    "parse-numbers": false
  }
}
```

**Comment by nexdrew** [comment]
@Alphapage Another workaround would be to configure your option as a string instead of an array:

```js
var argv = require('yargs')
  .option('a', {
    alias: 'arr',
    default: null,
    type: 'string'
  })
  .argv
console.log(argv.a)
```

And then specify multiple `-a` flags on the command line to construct an array:

```
$ node issue372.js -a .1 -a ''
[ '.1', '' ]
$ node issue372.js
null
```

**Comment by nexdrew** [comment]
Also see #166

**Comment by Alphapage** [comment]
@maxrimue It sounds great!
Why not:
```js
.array("a", {
        alias: "arr",
        default: null,
        parse-numbers: false
})
```

@nexdrew Sorry for the duplicate. The multiple flags is a valuable workaround, but it seems an ugly command line to me, so I will try @maxrimue solution first. 
Thank you anyway.

**Comment by maxrimue** [comment]
@Alphapage Have you tried the Alpha yet?

**Comment by Alphapage** [comment]
No I haven't tested. Mainly because of the global setting in package.json.I'm really waiting for a way to override parse-numbers locally in array options.

**Comment by bcoe** [comment]
@Alphapage I've moved this feature request here:

https://github.com/yargs/yargs-parser/issues/6

**Comment by gajus** [comment]
@bcoe What's the current way to say that a parameter is an array of type X?

By default, TypeScript types comes back as `(string | number)[]` – want to coerce into `string`.

**Comment by gajus** [comment]
Not sure if this is _the_ way, but for others reading, this worked:

```ts
omit: {
  default: [] as readonly string[],
  description:
    'Omit properties from the Roarr message, e.g. --omit context.version',
  type: 'array',
},
```

**Comment by pashakondratyev** [comment]
@gajus you can do 

```
omit: {
  string: true,
  description:
    'Omit properties from the Roarr message, e.g. --omit context.version',
  type: 'array',
},
```

**Comment by kopax** [comment]
> @gajus you can do
> 
> ```
> omit: {
>   string: true,
>   description:
>     'Omit properties from the Roarr message, e.g. --omit context.version',
>   type: 'array',
> },
> ```

This worked, thanks <3
