### ISSUE TITLE
How to get stack trace in case of an error?

### ISSUE THREAD

**Issue by gajus** [bcoe/yargs#373]
```js
#! /usr/bin/env node

import yargs from 'yargs';

yargs
    .fail((...args) => {
        console.log('args', args);
    })
    .command('lint', 'Report code format errors.', () => {
        throw new Error('test');
    })
    .argv;

```

Executing this code fails with `test` output. I am expecting `.fail()` to be called, but it is not. Is there a way to disable `yargs` error handler?

**Comment by gajus** [comment]
I have tried setting `.exitProcess(false)`, but the result is the same.

```js
#! /usr/bin/env node

import yargs from 'yargs';

yargs
    .fail((...args) => {
        console.log('args', args);
    })
    .exitProcess(false)
    .command('lint', 'Report code format errors.', () => {
        throw new Error('test');
    })
    .argv;
```

**Comment by gajus** [comment]
It looks like it all comes down to this (https://github.com/bcoe/yargs/blob/555b2f8560aaf27501a3abecb04855a38a24110b/index.js#L494-L507):

```js
Object.defineProperty(self, 'argv', {
  get: function () {
    var args = null

    try {
      args = parseArgs(processArgs)
    } catch (err) {
      usage.fail(err.message)
    }

    return args
  },
  enumerable: true
})
```

Ideally, there should be an option to re-throw the error.

**Comment by gajus** [comment]
In this case, the question is what overwrites `exitProcess`. I cannot figure it out using node debugger how on earth it gets overwritten.

**Comment by gajus** [comment]
<img width="342" alt="screen shot 2016-02-12 at 14 06 03" src="https://cloud.githubusercontent.com/assets/973543/13008988/cf972132-d191-11e5-8ad2-9b1eaca851b2.png">

I don't get what kind of magic is going on here.

```js
  var exitProcess = true
  self.exitProcess = function (enabled) {
    if (typeof enabled !== 'boolean') {
      enabled = true
    }
    exitProcess = enabled
    return self
  }
  self.getExitProcess = function () {
    return exitProcess
  }
```

`self.exitProcess` is executed only once. Yet, somehow, just after the error is thrown `exitProcess` suddenly gets `true` value.

**Comment by gajus** [comment]
```js
#! /usr/bin/env node

import yargs from 'yargs';

yargs
    .fail((...args) => {
        console.log('args 1', args);
    })
    .exitProcess(false)
    .command('lint', 'Report code format errors.', (subYargs) => {
        subYargs
            .exitProcess(false)
            .fail((...args) => {
                console.log('args 2', args);
            });
        throw new Error('test');
    })
    .argv;

```

That took some time to figure out.

**Comment by gajus** [comment]
Whatever yargs is doi

**Comment by gajus** [comment]
My question remains, because the stack trace that I get is in effect useless.

How do I get the original stack trace?

**Comment by gajus** [comment]
@bcoe Basically, passing the error object as the second parameter of the `fail()` handler would solve the issue (https://github.com/bcoe/yargs/pull/374).

I have not added the test cases for this. I have looked into the test files but did not find where you are testing the fail handler.

**Comment by bcoe** [comment]
@gajus this will go out the door with yargs 4.x.

**Comment by bcoe** [comment]
@gajus give it a spin:

`npm i yargs@next`

**Comment by venkatperi** [comment]
yargs@4.7.1 behaves the same. @gajus any luck at your end getting the stack trace?

**Comment by nexdrew** [comment]
@venkatperi You can define a custom `.fail()` handler which will be passed the original `Error` object (if any) as the 2nd argument. That `Error` will contain the full stacktrace. See [the docs](http://yargs.js.org/docs/index.html#methods-failfn) for an example or #382 for implementation details.
