### ISSUE TITLE
Array option behave differently

### ISSUE THREAD

**Issue by Alphapage** [bcoe/yargs#383]
Hello,

Here is my array option:
```js
.array("a", {
        alias: "arr",
        default: ['defaultvalue']
})
```
My command lines:
```js
node test.js -o blabla // argv.a ==null
node test.js -a -o blabla // argv.a ==null
node test.js -o blabla -a // argv.a.length ==0
node test.js -a insert -o blabla // argv.a.length ==1
```

The first command is correct of course.
The second command is incorrect to me, because it should give the same result as the third one.

Is it  a limitation because the parser doesn't know if -o is a string to insert or a command ?

Thanks in advance for your answers.

**Comment by maxrimue** [comment]
@Alphapage All these results seem just fine to me. `-o` is neither a command or string, it's a key for the `o` option, so is `-a` for `a`. If you write `-a -o blabla` that means: `a option, no value, o option, "blabla"`. What are you trying to accomplish?

**Comment by Alphapage** [comment]
```js
node test.js -a -o blabla // argv.a ==null
node test.js -o blabla -a // argv.a.length ==0
```
should be argv.a.length ==0 for both !

**Comment by maxrimue** [comment]
Ah I see, in the first example `argv.a` equals `undefined`, and in the second it equals an empty array. I'll have a look in some time what's going on.

**Comment by Alphapage** [comment]
Thank you for giving a little of your time to my problem.

**Comment by maxrimue** [comment]
While I'm not sure what _exactly_ caused your bug, I found a way for you to fix it. If you choose this configuration instead:
```javascript
var yargs = require('yargs');

var argv = yargs
.option("a", {
  alias: "arr",
  type: 'array',
  default: []
})
.argv;
```

You'll always get `[]` for `argv.a`, no matter if it's passed or not, the position also doesn't matter. Let's not close this issue yet though as the bug remains.

**Comment by Alphapage** [comment]
Great workaround to solve my problem. +100

**Comment by Alphapage** [comment]
Sorry, but I'm really fighting with this problem:
- when no -a in command line, then I want argv.a==null
- when -a only in command line, then I want argv.a.length==0
- when -a str1 str2 str3 in command line, then I want argv.a.length==3

Is it possible or is it a limitation ?

**Comment by maxrimue** [comment]
@Alphapage This usually is possible and definitely a bug. The array option should be `undefined` if the argument wasn't passed, and and empty array if it has been passed, but without any value, just like you expect it to be. I'm still not quite sure what causes this bug, but I'll look into this again today. Sorry for the mess.

**Comment by Alphapage** [comment]
I think the easiest way is to set an empty array inside eatArray function.
But the problem is how to propagate to aliases. I can't find how to do that.

**Comment by Alphapage** [comment]
Sorry I just read about your pullrequest: does it propagate to aliases too ?

**Comment by Alphapage** [comment]
Tested and it works great for aliases too. Thank you very much.
