### ISSUE TITLE
Variadic command arguments

### ISSUE THREAD

**Issue by alex-phillips** [bcoe/yargs#388]
First off, great work and congrats on v4!

A question regarding the new command syntax with named positional arguments. This is a great idea, but is there a way to have a variadic name argument with this syntax? Ex: `command <src...> <dest>` where `src` is a varying number of arguments, but the last argument is designated to `dest`.

**Comment by nexdrew** [comment]
@alex-phillips Great question! We [considered this](https://github.com/bcoe/yargs/issues/362#issue-130574013) (see question 4) but [decided not to implement it](https://github.com/bcoe/yargs/issues/362#issuecomment-183743341) (see 2nd bullet) for our first pass at positional arguments. We were kinda waiting to see if anyone would request this, and it sure didn't take long!

Perhaps we can take a look at adding this in soon. In the meantime, I think the best we can do is use a `type: 'array'` option for `src`:

```js
var argv = require('yargs')
  .command(
    'command <dest>',
    'Run a command against a destination',
    {
      src: {
        describe: 'One or more sources',
        type: 'array'
      }
    },
    function (argv) {
      console.log('src:', argv.src)
      console.log('dest:', argv.dest)
    }
  )
  .help().version()
  .argv
```

```sh
$ node issue388.js command d --src s1 s2 s3       
src: [ 's1', 's2', 's3' ]
dest: d
```

**Comment by alex-phillips** [comment]
Cool, thanks for the prompt reply! I'm using it as an argument currently instead of an option, so I'll just stick to my current usage (slicing the array in the handler).

Keep up the good work! Love the project.
