### ISSUE TITLE
TypeError: Cannot read property 'filename' of undefined (require.main is undefined)

### ISSUE THREAD

**Issue by kumar303** [bcoe/yargs#390]
I upgraded yargs from 3.32.0 to 4.1.0 and got this trace when constructing a `yargs` object and executing it from a test:
````
TypeError: Cannot read property 'filename' of undefined
      at isIISNode (node_modules/require-main-filename/index.js:8:33)
      at module.exports (node_modules/require-main-filename/index.js:3:7)
      at parseArgs (node_modules/yargs/index.js:576:12)
      at Object.Argv.self.showHelp (node_modules/yargs/index.js:424:23)
      at Object.self.fail (node_modules/yargs/lib/usage.js:43:35)
      at Object.Argv.Object.defineProperty.get [as argv] (node_modules/yargs/index.js:563:15)
      at Program.run (dist/webpack:/src/cli.js:30:16)
      at Context.<anonymous> (dist/webpack:/tests/cli/test.cli.js:21:20)
````

I can  see that `require.main` is undefined at this point which is causing the error. I'm using webpack (queue dramatic music) but from what I can tell it is configured correctly to define `require.main`. However, it is only defined when running a script on the command line. In my test program, `require.main` is not defined within the `require-main-filename` module. My tests are loaded and run from a [context](https://webpack.github.io/docs/context.html) which may be at play here.

It looks like `requireMainFilename()` was introduced [here](https://github.com/bcoe/yargs/commit/fb161e2f7bd6520e31f4843ba1d753c8799fb67a) and one difference is that `require.main` is accessed from a nested dependency now.

I can't tell if this is a webpack issue or a yargs issue. Is it possible to be more defensive about `require.main.filename` ?

**Comment by bcoe** [comment]
@kumar303 being more defensive in yargs seems like the right thing, I'll get a patch out tonight; and would love to work with you to test this :)

**Comment by bcoe** [comment]
@kumar303 could you delete your `node_modules` folder, and try installing `yargs@latest` again?

I've released a patch for this behavior:

https://github.com/yargs/require-main-filename/pull/2

**Comment by kumar303** [comment]
Thanks for the quick fix! It is working great. Since `require-main-filename` was not strictly pinned in yargs, the change was already picked up. To reproduce the bug, I did this: https://github.com/kumar303/web-ext/commit/948d3f451b9aec8b09ab2bb1410cd915bc8d23b3 (which failed: https://travis-ci.org/mozilla/web-ext/jobs/110167764) and then when I upgraded, my tests passed. Thanks again.
