### ISSUE TITLE
$0 reports "node" when run via "/usr/bin/env node"

### ISSUE THREAD

**Issue by boneskull** [bcoe/yargs#48]
I have

```sh
#!/usr/bin/env node
```

At the top of my CLI script, but `$0` reports `node` as the program.  Anything to be done here?

**Comment by bcoe** [comment]
@boneskull, as I gather it `$0` is meant largely for documentation purposes:

`.usage('Usage: $0 -x [num] -y [num]')`

It seems like it would be kind of weird to have the environment prefix included:

`.usage('Usage: /usr/bin/env my-bin -x [num] -y [num]');

Do you have a use-case in mind for maintaining the environment prefix?

**Comment by bcoe** [comment]
@boneskull bump, see my previous comment.

**Comment by boneskull** [comment]
@bcoe Hmm, I think I wasn't clear.  I don't want either of those things.  

Here's a trivial example:

```js
#!/usr/bin/env node

var yargs = require('yargs').usage('$0 --bar --baz');
console.log(yargs.help());
```

Create this file, `foo`, `chmod +x` it, then `./foo`.  Executing `node foo` is the same result.

So my suggestion would be: don't look at `process.argv[0]` for `$0`, and instead use `path.basename(process.argv[1])`.  Yeah?

**Comment by raine** [comment]
For me it's showing `Usage: /usr/local/bin/foo`.

Why the whole path?

**Comment by bcoe** [comment]
@boneskull I agree I don't see why we can't simplify the logic to use basename/process.argv[0]. Thoughts @chevex, @nylen?

**Comment by boneskull** [comment]
@raine I wonder what's different about my setup that I always see `node` in front of it.

**Comment by bcoe** [comment]
@raine @boneskull, in both cases could we just trim it to: `foo`?

**Comment by raine** [comment]
@boneskull 

I used to **not** get `node` in front with my previous startup script:

```js
#!/usr/bin/env node
require('gnode');
require('../lib');
```

`Usage: /usr/local/bin/foo <command> [options]`

With the new script I do get the `node` as well:

```js
#!/bin/sh
":" //# comment; exec /usr/bin/env node --harmony "$0" "$@"
require('../lib');
```

`Usage: node /usr/local/bin/foo <command> [options]`

@bcoe, I think that makes most sense

**Comment by bcoe** [comment]
@raine my preference would generally be to have `$0` be the application name, since I tend to install CLI apps with `npm install foo -g`. and would expect:

`Usage: foo <command> [options]`

I like the simplicity of `path.basename(process.argv[1])`, thoughts?

**Comment by raine** [comment]
yep, I share that preference

**Comment by bcoe** [comment]
@raine @boneskull I've added support for bash completions on this branch:

https://github.com/bcoe/yargs/pull/118

In the process I modified how $0 is calculated slightly, in such a way that it works well for bash completion:

`node ./bin/foo.js` becomes `bin/foo.js`.
`node ./foo.js` becomes `foo.js`.

Once installed as a global bin, `$0` should equal your application's name. Let me know if this solves most of your $0 problems, I think this is a good compromise. Also, give bash completions a spin.

**Comment by bcoe** [comment]
to try out the new $0 behavior, give yargs' slick new completion functionality a shot and let me know what you think:

https://github.com/bcoe/yargs#completioncmd-description-fn

It's published to the `next` tag on npm.

`npm install yargs@next`

**Comment by rstacruz** [comment]
:+1: on passing it to basename.

I was using 3.7.0 and got this:

```
gh-annotate — master • ./bin/gh-annotate --help
Usage:
../../../.nvm/versions/io.js/v1.6.2/bin/iojs bin/gh-annotate <file>
... | ../../../.nvm/versions/io.js/v1.6.2/bin/iojs bin/gh-annotate
```
