### ISSUE TITLE
yargs@1.3.3: invalid parsing of options whose single-quoted value contains hyphen/dash

### ISSUE THREAD

**Issue by mikermcneil** [bcoe/yargs#78]
> Originally posted here: https://github.com/chevex/yargs/issues/20#issuecomment-72668101

When parsing stuff like:

```sh
machinepack exec get-price-estimate --apiKey='asdg' --startLatitude='123' --startLongitude='23' --endLatitude='-13' --endLongitude='13'
```
Rather than as the value of `endLongitude`, `-13` gets parsed as two separate options: `3: true` and `1:true`, while endLatitude ends up being true as well.

**Comment by bcoe** [comment]
@mikermcneil could you share a snippet of code that causes this for me, I ran the following program:

```js
var yargs = require('./');

console.log(yargs.argv);
```

With the arguments:

```bash
machinepack exec get-price-estimate --apiKey='asdg' --startLatitude='123' --startLongitude='23' --endLatitude='-13' --endLongitude='13'
```

And the output was:

```javascript
{ _: [],
  apiKey: 'asdg',
  startLatitude: 123,
  startLongitude: 23,
  endLatitude: -13,
  endLongitude: 13,
  '$0': 'node ./test.js' }
```

This is running against the `master` branch.

**Comment by mikermcneil** [comment]
@bcoe thanks for the reply, and sorry about my slow follow up.  I'm having this problem w/ `yargs@1.3.3`, which it appears is no longer the latest stable.  @irlnathan or I will give it another go w/ the latest from npm (and if that doesn't work, we'll try master)

As for a code snippet, it's not particularly exciting- just [this](https://github.com/node-machine/machinepack/blob/master/bin/machinepack-exec.js#L14)

**Comment by bcoe** [comment]
@mikermcneil any luck with 3.x?

**Comment by calendee** [comment]
@bcoe Having the same problem as @mikermcneil .  Dealing with Firebase id's.

yargs : 3.3.1

Sample where I just `console.log(argv)`
```
node index.js --memberOneId "-Jix2ddpuZd34PvMs0e8" --memberTwoId "-Jix2dnnmL1bRCIHFl3i"
{ '1': true,
  '2': true,
  '3': true,
  _: [],
  memberOneId: true,
  J: [ 'ix2ddpuZd34PvMs0e8', true ],
  memberTwoId: true,
  i: true,
  x: true,
  d: true,
  n: true,
  m: true,
  L: true,
  b: true,
  R: true,
  C: true,
  I: true,
  H: true,
  F: true,
  l: true,
  '$0': 'node index.js' }
```

**Comment by calendee** [comment]
It all starts to fall apart in Line 125 of `parser.js` with this code : 

`else if (arg.match(/^-[^-]+/)) {`

**Comment by calendee** [comment]
FYI : My "fix" for this is to use "=" in the arguments like : 

```
node index.js --memberOneId=-Jix2ddpuZd34PvMs0e8 --memberTwoId=-Jix2dnnmL1bRCIHFl3i
```

Then, I get the proper output:
```
{ _: [],
  memberOneId: '-Jix2ddpuZd34PvMs0e8',
  memberTwoId: '-Jix2dnnmL1bRCIHFl3i',
  '$0': 'node index.js' }
```

**Comment by bcoe** [comment]
@calendee gotcha, the underlying problem is that that the argument is ambiguous:

`--foo -bar`

could be the boolean key `--foo` and the boolean key `-bar`, or the key `--foo` with the value `-bar`.

What if we implemented this feature:

https://github.com/bcoe/yargs/issues/15

This would allow us to specify that one argument must follow a key that we know will have tokens as values.

**Comment by calendee** [comment]
@bcoe Understood.  Yep, that would work for me.

**Comment by bcoe** [comment]
@calendee @mikermcneil give https://github.com/bcoe/yargs/pull/105 a spin:

`npm install yargs@next`

It gives you the ability to specify `nargs`, which can be used to handle ambiguous situations like the one described:

```js
var argv = require('./')
  .usage('\nUsage: $0 -memberOneId [string] -memberTwoId [pipe delimited string]')
  .nargs('memberOneId', 1)
  .nargs('memberTwoId', 1)
  .demand(['memberOneId','memberTwoId'])
  .argv;
```

**Comment by bcoe** [comment]
I've implemented the `nargs` feature here:

https://github.com/bcoe/yargs/pull/105

Which allows you to specify a required argument count of 1 for ambiguous arguments. I think this should solve both problems discussed in this thred.
