### ISSUE TITLE
yargs' documentation needs your help to make it better

### ISSUE THREAD

**Issue by billev2k** [bcoe/yargs#92]
The pirate talk is cute, but ... ultimately detracts from the usability of the documentation, and thus, the product. It's particularly difficult for anyone for whom pirate english is not their first language. Which is most of us.

Please create documentation that's designed to communicate how to use the code.

**Comment by mikermcneil** [comment]
> difficult for anyone for whom pirate english is not their first language

@billev2k  haha awesome :)

> Please create documentation that's designed to communicate how to use the code.

Not sure I agree that the pirate speak `ultimately detracts from the usability of the documentation`, but you're totally right that the README could do a better job explaining the usage of this module.  @chevex: If it would be helpful, @irlnathan and I are willing to spend a bit of time enhancing the readme (and just to clarify, "enhancing" !== "removing pirate speak" :)  )

**Comment by bcoe** [comment]
@billev2k tis a mighty fine point, and I tend to be agreen' with ya.

Personally I love the pirate theme, it's fun. But, I think we could celebrate pirate roots of yargs in the first few paragraphs, while tightening up the bulk of the documentation. Personally I would like to see:

* a pirate-themed intro.
* a few well documented real-world examples of the yargs DSL in action (sans pirate talk).
* thorough, standardized, documentation of all the API methods. (sans pirate talk).

What do you think?

**Comment by acstll** [comment]
I just read the entire README and I don't mind the pirate talk but I was like "please just show me the API".

So +1 for this:

> - a pirate-themed intro.
> - a few well documented real-world examples of the yargs DSL in action (sans pirate talk).
> - thorough, standardized, documentation of all the API methods. (sans pirate talk).

**Comment by bcoe** [comment]
@acstll, @billev2k, @mikermcneil I agree with everyone in this thread. I would love some help trimming down the README a bit. patches more than welcome.

**Comment by ejosafat** [comment]
I agree with the idea of pirate lingo being cute, but when english is not your native language, well, it gets too difficult to understand the documentation when you first have to translate from pirate to english, you spend so much effort doing it!!

**Comment by nexdrew** [comment]
@bcoe What do you think about reorganizing the README content into a format similar to [the standard-readme draft](https://github.com/zcei/standard-readme/issues/1)?

Would basically be something like:

```
(Heading Block)
# yargs
![badges]
Piratey description

(Install Block)
# Install
How to install

(Usage/Example Block)
# Examples
Minimal examples?
Show most common usages

(API Block)
# API
## method signature
Description
- Return type?
- Arguments
Example?

(License Block)
# License
Name/Desc/Link (SPDX)
```

I don't want you to waste too much time on this, but you could also check out [the original discussion](https://github.com/feross/standard/issues/141) that sparked the standard-readme repo. Sounds like getting everyone to agree is gonna be difficult, but I like the idea.

**Comment by bcoe** [comment]
@nexdrew I like this idea, and will read through the discussion tomorrow. standard-readme is new to me, but it looks like a good initiative.

One random thought, it would be good to alphabetize the API listing!

**Comment by nexdrew** [comment]
Mind: :boom:

Sounds like perhaps we should tackle this incrementally. I'll see if I can put together a PR or 2 as the week goes on.

**Comment by bcoe** [comment]
@nexdrew I like your proposed layout, I think it would be a huge improvement to sure-up the README in this way.

**Comment by Rojuinex** [comment]
100% agree pirate speak detracts from understandability.  I actually found this issue by googling "yargs tutorial without pirate speak" because the docs require way to much brain power to process the pirate speak than I care to give atm.

**Comment by bcoe** [comment]
We've been working on a yargs website that will introduce folks to the project without the pirate speak:

https://github.com/yargs/yargs.github.io/issues/1

Closing this issue in favor of the documentation conversation happening on the issue linked above.
